import { createContext, useContext, useState, useEffect, type ReactNode } from "react";
import { translations, LANGS, type Lang } from "../data/translations";

const extraTranslations: Record<Lang, Record<string, string>> = {
  tr: {
    "quick.badge": "OSM Ekonomi Rehberi",
    "quick.titleA": "Hızlı Satış",
    "quick.titleB": "Tekniği",
    "quick.desc": "Oyuncu değerini yaz, yaş grubunu seç, transfer listesine koyacağın en mantıklı hızlı satış fiyatını anında hesapla.",
    "quick.player": "Oyuncu ismi",
    "quick.value": "Şu anki değeri",
    "quick.recommended": "Önerilen Liste Fiyatı",
    "quick.forPlayer": "için",
    "quick.withMultiplier": "çarpanla önerilen fiyat.",
    "quick.marketValue": "Piyasa değeri",
    "quick.cashLevel": "Acil nakit seviyesi",
    "quick.testRange": "Piyasa test bandı",
    "quick.young": "Genç Oyuncular",
    "quick.prime": "Orta Yaş",
    "quick.senior": "Kıdemli Oyuncular",
    "quick.youngNote": "Gelişim hızı yüksek olduğu için en hızlı alıcı bulan grup.",
    "quick.primeNote": "2.0x - 2.2x bandı dengeli ve güvenli satış sağlar.",
    "quick.seniorNote": "Değer artışı yavaşladığı için daha düşük çarpan gerekir.",
    "quick.best": "En iyi hızlı fiyat",
    "quick.fast": "Acil nakit",
    "quick.test": "Piyasa testi",
    "quick.bestDesc": "Yaşa göre agresif ama satılabilir hedef fiyat.",
    "quick.fastDesc": "Para gerekiyorsa satışı tetikleyen düşük riskli seviye.",
    "quick.testDesc": "Satılmayan oyuncuda 1.10x - 1.05x bandını dene.",

    "matches.nav": "Günün Maçları",
    "matches.badge": "Topluluk Tahmini",
    "matches.titleA": "Günün",
    "matches.titleB": "Maçları",
    "matches.desc": "Siteye girenler bugünün maçları için tahmin yapar. Oy oranları Firebase üzerinden anlık güncellenir.",
    "matches.emptyTitle": "Bugün için maç eklenmemiş",
    "matches.emptyText": "Admin panelinden bugünün maçlarını eklediğinde burada görünecek.",
    "matches.adminToggleOpen": "Maç admin paneli aç",
    "matches.adminToggleClose": "Maç admin paneli gizle",
    "matches.adminEmail": "Admin email",
    "matches.password": "Şifre",
    "matches.login": "Giriş",
    "matches.loggedIn": "Giriş yapıldı:",
    "matches.logout": "Çıkış",
    "matches.teamA": "Takım 1",
    "matches.teamB": "Takım 2",
    "matches.competition": "Turnuva",
    "matches.omerPickInput": "Ömer'in tahmini (opsiyonel)",
    "matches.add": "Maç Ekle",
    "matches.close": "Kapat",
    "matches.open": "Aç",
    "matches.delete": "Sil",
    "matches.openStatus": "Tahmine açık",
    "matches.closedStatus": "Tahmin kapalı",
    "matches.votes": "oy",
    "matches.draw": "Beraberlik",
    "matches.saved": "Tahminin kaydedildi",
    "matches.omerPick": "Ömer'in tahmini:",
    "matches.loginError": "Admin girişi başarısız. Email/şifreyi kontrol et.",
    "matches.teamError": "Takım isimlerini yazman gerekiyor.",
    "matches.addError": "Maç eklenemedi. Firestore rules ve admin girişini kontrol et.",
    "matches.voteError": "Tahmin gönderilemedi. Rules ayarlarını kontrol et.",

    "comments.badge": "Topluluk",
    "comments.titleA": "Kullanıcı",
    "comments.titleB": "Yorumları",
    "comments.desc": "Yorumlar önce onaya düşer. Ömer onayladıktan sonra sitede görünür.",
    "comments.write": "Yorum Yaz",
    "comments.manager": "Menajer adı",
    "comments.rating": "Puan",
    "comments.message": "Mesaj",
    "comments.placeholderName": "Nickiniz",
    "comments.placeholderMessage": "Taktiği nerede denedin? Sonuç ne oldu?",
    "comments.submit": "Yorumu Gönder",
    "comments.sending": "Gönderiliyor...",
    "comments.sent": "Yorumun gönderildi. Onaydan sonra yayınlanacak.",
    "comments.empty": "İlk onaylı yorumu bekliyoruz.",
    "comments.none": "Henüz onaylanmış yorum yok.",
    "comments.total": "Toplam {count} onaylanmış yorum var.",
    "comments.adminOpen": "Admin yorum onayı aç",
    "comments.adminClose": "Admin yorum onayı gizle",
    "comments.pendingNone": "Bekleyen yorum yok.",
    "comments.approve": "Onayla",
    "comments.delete": "Sil",
    "comments.errorInvalid": "Lütfen geçerli bir menajer adı ve yorum yaz.",
    "comments.errorSend": "Yorum gönderilemedi. Firebase ayarlarını ve Firestore kurallarını kontrol et.",
    "comments.errorLogin": "Admin girişi başarısız. Firebase Authentication kullanıcını kontrol et.",
  },
  en: {
    "quick.badge": "OSM Economy Guide", "quick.titleA": "Quick Sale", "quick.titleB": "Technique", "quick.desc": "Enter the player value, choose the age group, and instantly calculate the best transfer list price.", "quick.player": "Player name", "quick.value": "Current value", "quick.recommended": "Recommended List Price", "quick.forPlayer": "for", "quick.withMultiplier": "with the selected multiplier.", "quick.marketValue": "Market value", "quick.cashLevel": "Emergency cash level", "quick.testRange": "Market test range", "quick.young": "Young Players", "quick.prime": "Prime Age", "quick.senior": "Senior Players", "quick.youngNote": "High growth potential makes this the fastest-selling group.", "quick.primeNote": "The 2.0x - 2.2x range gives balanced sales.", "quick.seniorNote": "Lower multipliers are needed because value growth slows down.", "quick.best": "Best quick price", "quick.fast": "Emergency cash", "quick.test": "Market test", "quick.bestDesc": "Aggressive but sellable target price by age.", "quick.fastDesc": "A low-risk level to trigger a sale when cash is needed.", "quick.testDesc": "Use 1.10x - 1.05x for players who do not sell.",
    "matches.nav": "Daily Matches", "matches.badge": "Community Prediction", "matches.titleA": "Daily", "matches.titleB": "Matches", "matches.desc": "Visitors vote on today's matches. Percentages update live through Firebase.", "matches.emptyTitle": "No matches added for today", "matches.emptyText": "Matches will appear here when you add today's fixtures from the admin panel.", "matches.adminToggleOpen": "Open match admin panel", "matches.adminToggleClose": "Hide match admin panel", "matches.adminEmail": "Admin email", "matches.password": "Password", "matches.login": "Login", "matches.loggedIn": "Logged in:", "matches.logout": "Logout", "matches.teamA": "Team 1", "matches.teamB": "Team 2", "matches.competition": "Competition", "matches.omerPickInput": "Omer's pick (optional)", "matches.add": "Add Match", "matches.close": "Close", "matches.open": "Open", "matches.delete": "Delete", "matches.openStatus": "Prediction open", "matches.closedStatus": "Prediction closed", "matches.votes": "votes", "matches.draw": "Draw", "matches.saved": "Your prediction is saved", "matches.omerPick": "Omer's pick:", "matches.loginError": "Admin login failed. Check email/password.", "matches.teamError": "You need to enter team names.", "matches.addError": "Match could not be added. Check Firestore rules and admin login.", "matches.voteError": "Prediction could not be sent. Check rules.",
    "comments.badge": "Community", "comments.titleA": "User", "comments.titleB": "Comments", "comments.desc": "Comments wait for approval first. They appear after Omer approves them.", "comments.write": "Write a Comment", "comments.manager": "Manager name", "comments.rating": "Rating", "comments.message": "Message", "comments.placeholderName": "Your nick", "comments.placeholderMessage": "Where did you try the tactic? What was the result?", "comments.submit": "Submit Comment", "comments.sending": "Sending...", "comments.sent": "Your comment was sent. It will be published after approval.", "comments.empty": "Waiting for the first approved comment.", "comments.none": "No approved comments yet.", "comments.total": "Total {count} approved comments.", "comments.adminOpen": "Open admin approval", "comments.adminClose": "Hide admin approval", "comments.pendingNone": "No pending comments.", "comments.approve": "Approve", "comments.delete": "Delete", "comments.errorInvalid": "Please enter a valid manager name and comment.", "comments.errorSend": "Comment could not be sent. Check Firebase settings and Firestore rules.", "comments.errorLogin": "Admin login failed. Check Firebase Authentication user.",
  },
  hu: {},
  ar: {},
  pt: {},
};

extraTranslations.hu = { ...extraTranslations.en, "matches.nav": "Napi Meccsek", "quick.titleA": "Gyors Eladás", "quick.titleB": "Technika", "comments.titleB": "Hozzászólások" };
extraTranslations.ar = { ...extraTranslations.en, "matches.nav": "مباريات اليوم", "quick.titleA": "بيع سريع", "quick.titleB": "تقنية", "comments.titleB": "التعليقات" };
extraTranslations.pt = { ...extraTranslations.en, "matches.nav": "Jogos do Dia", "quick.titleA": "Venda Rápida", "quick.titleB": "Técnica", "comments.titleB": "Comentários" };

Object.assign(extraTranslations.tr, {
  "nav.squad": "Kadro Analiz",
  "nav.tools": "Araçlar",
  "nav.premium": "Premium",
  "nav.donate": "Destek Ol",
  "nav.login": "Giriş",
  "nav.signup": "Üye Ol",
  "nav.profile": "Profilim",
  "nav.leaderboard": "Liderlik",
  "profile.modalTitle": "Manager Girişi / Üye Ol",
  "videos.badge": "Video Rehberler",
  "videos.title1": "YouTube",
  "videos.title2": "Kanalı",
  "videos.desc": "Taktiklerin saha üstünde nasıl uygulandığını videolarla izle. Yeni içerikler için abone ol.",
  "videos.subscribe": "YouTube'a Abone Ol",
  "daily.badge": "Günün Taktiği",
  "leader.badge": "Liderlik Tablosu",
  "leader.title1": "Top Manager",
  "leader.title2": "Sıralaması",
  "leader.desc": "Maç tahminlerinden doğru bilen +10 puan kazanır. En çok puan toplayan zirvede!",
  "leader.yourRank": "Senin Sıran",
  "leader.notRanked": "Henüz sıralamada değilsin",
  "leader.predict": "Tahmin Yap",
  "leader.loading": "Yükleniyor...",
  "leader.empty": "Henüz hiç tahmin yapan yok. İlk sen ol!",
  "leader.signInPrompt": "Sıralamada görünmek için üye ol ve maç tahminleri yap.",
  "nav.blog": "Rehberler",
  "blog.badge": "Rehber & Blog",
  "blog.title1": "OSM",
  "blog.title2": "Rehberleri",
  "blog.desc": "Her formasyon ve strateji için detaylı rehberler. Google'da en çok aranan OSM soruları burada.",
  "anti.reset": "Sıfırla",
  "anti.opponent": "Rakip:",
  "anti.youLabel": "Senin Taktiğin",
  "anti.oppLabel": "Rakip Formasyonu",
  "anti.fieldTested": "Saha Testi",
  "anti.waitingTitle": "Rakibinin Dizilişini ve Mentalitesini Seç",
  "anti.waitingText": "Arkanıza yaslanın, rahatlayın ve yapay zekanın size kazandıracak kontra taktiği üretmesine izin verin.",
  "about.legacyBadge": "Miras ve Geçmiş",
  "about.legacyTitleA": "16 YIL",
  "about.legacyTitleB": "OYUNUN İÇİNDE.",
  "about.legacyP1": "2009'dan 2026'ya kadar bu oyunda hemen hemen her şeyi gördüm. Efsane SOA Crew üyesi olarak dünya sıralamasında iki yıl boyunca 1 numarada kaldık.",
  "about.legacyP2": "İlk hesabımı kaybetmiş olabilirim, ama tecrübe hâlâ burada. Şu an İngiltere'de yaşıyorum; oyunu sevdiğim için oynuyor ve mirasımı paylaşmak istiyorum.",
  "about.noticeTitle": "Önemli Uyarı ve Tavsiye",
  "about.noMagicTitle": "Sihirli taktik yok",
  "about.noMagicP1": "Bu oyunda sabit veya yenilmez bir taktik yoktur. Lütfen benden özelden yenilmemezlik taktiği istemeyin.",
  "about.noMagicP2": "Hiç kaybetmeyen taktik diye bir şey yoktur. Böyle bir şey iddia edenlere inanmayın.",
  "about.logicTitle": "Mantık ve Adaptasyon",
  "about.logicP1": "Bu oyun bir gecede öğrenilecek bir oyun değildir. Mantık, strateji ve analiz ister.",
  "about.logicP2": "Boş liglere tek başına girmek yerine, dolu ve rekabetçi liglerde taktik test edin.",
  "about.quoteA": "Ligi kazanmak en güçlü kadroya sahip olmak değildir;",
  "about.quoteB": "detayları yönetmektir.",
  "about.quoteP": "2009'dan beri birçok menajerin internette bulduğu kopya taktiklere güvendiği için kaybettiğini gördüm. Üst düzey liglerde en büyük silahın esnekliktir.",
  "social.youtube": "YouTube Kanalı",
  "social.instagram": "Instagram Profili",
  "social.facebook": "Facebook Profili",
  "footer.comments": "Yorumlar",
  // SquadAnalyzer
  "squad.badge": "Kadro Analiz Aracı",
  "squad.title1": "Kadro",
  "squad.title2": "Değeri Analizi",
  "squad.desc": "Kendi kadro değerini ve rakibin değerini gir. Sistem güç durumunu hesaplar ve sana en uygun hazır anti-taktiği önerir.",
  "squad.myValue": "Senin Kadro Değerin",
  "squad.oppValue": "Rakibin Kadro Değeri",
  "squad.oppTactic": "Rakip Taktiği",
  "squad.strength": "Güç Durumu",
  "squad.stronger": "Güçlüsün ⭐",
  "squad.equal": "Eşitsin ⚖️",
  "squad.weaker": "Zayıfsın ⚠️",
  "squad.recommended": "Önerilen Anti-Taktik",
  "squad.openEngine": "Detaylı çizgi taktikleri için Anti-Taktik motorunu aç →",
  "squad.noResult": "Bu kombinasyon için hazır taktik bulunamadı. Anti-Taktik motorundan manuel seçim yapabilirsin.",
  // WeeklyMeta
  "meta.badge": "Haftanın Meta Taktiği",
  "meta.winRate": "Kazanma Oranı",
  "meta.openEngine": "Anti-Taktik Motorunu Aç",
  // PremiumTactics
  "premium.badge": "🔒 VIP Bölüm",
  "premium.title1": "Premium",
  "premium.title2": "Taktikler",
  "premium.desc": "Final, kupa ve özel maçlar için Ömer'in kişisel VIP taktik koleksiyonu.",
  "premium.active": "✓ Premium Aktif",
  "premium.exit": "Çıkış",
  "premium.unlockTitle": "VIP Taktiklerin kilidini aç",
  "premium.unlockDesc": "Premium üyelik ile tüm özel taktiklere erişirsin. Üye olduktan sonra sana özel kodu girerek kilidi açabilirsin.",
  "premium.becomePremium": "💎 Premium Ol",
  "premium.codeLabel": "Kod ile aç",
  "premium.codePlaceholder": "Premium kodun",
  "premium.unlock": "Kilidi Aç",
  "premium.wrongCode": "Kod hatalı. Tekrar dene.",
  "premium.required": "Premium Gerekli",
  // DailyTactic
  "daily.openEngine": "Anti-Taktik Motorunu Aç →",
  // Blog
  "blog.readMore": "Devamını Oku →",
  "blog.backToGuides": "← Tüm Rehberler",
  "blog.tryCta": "Bu taktiklerin tamamını Anti-Taktik Motorunda dene!",
  "blog.openEngine": "Anti-Taktik Motorunu Aç",
  // Navbar
  "nav.menu": "Menü",
  "nav.close": "Kapat",
  "nav.theme": "Tema",
  "nav.lang": "Dil",
  // ManagerTools
  "tools.badge": "Menajer Araçları",
  "tools.title1": "Menajer",
  "tools.title2": "Araç Kutusu",
  "tools.tab.referee": "Hakem Rehberi",
  "tools.tab.training": "Antrenman",
  "tools.tab.transfer": "Transfer Rehberi",
  "tools.tab.league": "Lig Hedefi",
  "tools.tab.checklist": "Maç Öncesi",
  "tools.ref.title": "Hakem Sertliği Rehberi",
  "tools.ref.desc": "Hakemin rengine göre sertlik ayarını yap. Renk ne kadar sıcaksa hakem o kadar sert.",
  "tools.ref.advice": "Tavsiye:",
  "tools.ref.tackling": "Önerilen sertlik:",
  "tools.train.title": "Kamp / Antrenman Önerici",
  "tools.train.desc": "Oyuncunun yaşına göre kamp, antrenman ve gizli antrenman önerisi.",
  "tools.train.years": "yaş",
  "tools.transfer.title": "Transfer Alım Rehberi",
  "tools.transfer.desc": "Oynadığın dizilişi seç, hangi mevkiye nasıl oyuncu alman gerektiğini gör.",
  "tools.league.title": "Lig Hedefi Planlayıcı",
  "tools.league.desc": "Hedefine ulaşmak için kaç maç kazanman gerektiğini hesapla.",
  "tools.league.total": "Toplam maç",
  "tools.league.played": "Oynanan maç",
  "tools.league.current": "Mevcut puan",
  "tools.league.target": "Hedef puan",
  "tools.league.remaining": "Kalan maç",
  "tools.league.needed": "Gereken puan",
  "tools.league.wins": "Gereken galibiyet",
  "tools.league.perMatch": "Maç başı gereken ort.",
  "tools.league.reachable": "✅ Hedef ulaşılabilir",
  "tools.league.hard": "⚠️ Hedef matematiksel olarak zor",
  "tools.checklist.title": "Maç Öncesi Kontrol Listesi",
  "tools.checklist.desc": "Maça çıkmadan önce hepsini kontrol et.",
  // Hero CTA buttons
  "hero.findAntiTactic": "Anti-Taktik Bul",
  "hero.quickSale": "Hızlı Satış Tekniği",
  "hero.support": "Destek",
  // Manager mascot badge labels
  "hero.badge.winRate": "GALİBİYET",
  "hero.badge.worldRank": "DÜNYA SIRASI",
  "hero.badge.matches": "MAÇ",
  "hero.badge.trophy": "KUPA",
  "hero.badge.battlePoint": "SAVAŞ PUANI",
  "hero.badge.experience": "TECRÜBE",
});

Object.assign(extraTranslations.en, {
  "nav.squad": "Squad Analysis",
  "nav.tools": "Tools",
  "nav.premium": "Premium",
  "nav.donate": "Support",
  "nav.login": "Sign in",
  "nav.signup": "Sign up",
  "nav.profile": "My Profile",
  "nav.leaderboard": "Leaderboard",
  "profile.modalTitle": "Sign in / Sign up",
  "videos.badge": "Video Guides",
  "videos.title1": "YouTube",
  "videos.title2": "Channel",
  "videos.desc": "Watch how tactics are applied on the field. Subscribe for new content.",
  "videos.subscribe": "Subscribe to YouTube",
  "daily.badge": "Daily Tactic",
  "leader.badge": "Leaderboard",
  "leader.title1": "Top Manager",
  "leader.title2": "Rankings",
  "leader.desc": "Correct match predictions earn +10 points. The highest scorer leads the board!",
  "leader.yourRank": "Your Rank",
  "leader.notRanked": "Not ranked yet",
  "leader.predict": "Predict Now",
  "leader.loading": "Loading...",
  "leader.empty": "No predictions yet. Be the first!",
  "leader.signInPrompt": "Sign up and make match predictions to appear on the leaderboard.",
  "nav.blog": "Guides",
  "blog.badge": "Guides & Blog",
  "blog.title1": "OSM",
  "blog.title2": "Guides",
  "blog.desc": "Detailed guides for every formation and strategy. The most searched OSM questions answered here.",
  "anti.reset": "Reset",
  "anti.opponent": "Opponent:",
  "anti.youLabel": "Your Tactic",
  "anti.oppLabel": "Opponent Formation",
  "anti.fieldTested": "Field Tested",
  "anti.waitingTitle": "Select Opponent's Formation & Mentality",
  "anti.waitingText": "Sit back, relax, and let the AI generate your winning counter-tactic.",
  "about.legacyBadge": "Legacy & History",
  "about.legacyTitleA": "16 YEARS",
  "about.legacyTitleB": "IN THE GAME.",
  "about.legacyP1": "From 2009 to 2026, I’ve seen it all. As a member of the legendary SOA Crew, we dominated the world rankings at No. 1 for two straight years.",
  "about.legacyP2": "I may have lost my first account, but the experience remains. Now residing in England, I play for the love of the game and to share my legacy.",
  "about.noticeTitle": "Important Notice & Advice",
  "about.noMagicTitle": "No magic tactics",
  "about.noMagicP1": "There is no fixed or unbeatable tactic in this game. Please do not message me privately asking for such things.",
  "about.noMagicP2": "There is no tactic that never loses. Do not believe anyone claiming to have an unbeatable strategy.",
  "about.logicTitle": "Logic & Adaptation",
  "about.logicP1": "This is not a game you can master overnight. It requires logic, strategy and analysis.",
  "about.logicP2": "Avoid empty leagues; join full competitive leagues to test tactics and counter-strategies.",
  "about.quoteA": "Winning a league is not about having the strongest squad;",
  "about.quoteB": "it is about managing the details.",
  "about.quoteP": "Since 2009, I have seen many managers fail because they relied on copy-paste tactics. In high-level leagues, flexibility is your greatest weapon.",
  "social.youtube": "YouTube Channel",
  "social.instagram": "Instagram Profile",
  "social.facebook": "Facebook Profile",
  "footer.comments": "Comments",
  // SquadAnalyzer
  "squad.badge": "Squad Analysis Tool",
  "squad.title1": "Squad",
  "squad.title2": "Value Analysis",
  "squad.desc": "Enter your squad value and your opponent's. The system calculates the power balance and recommends the best counter-tactic.",
  "squad.myValue": "Your Squad Value",
  "squad.oppValue": "Opponent Squad Value",
  "squad.oppTactic": "Opponent Tactic",
  "squad.strength": "Power Balance",
  "squad.stronger": "You're Stronger ⭐",
  "squad.equal": "Even Match ⚖️",
  "squad.weaker": "You're Weaker ⚠️",
  "squad.recommended": "Recommended Anti-Tactic",
  "squad.openEngine": "Open Anti-Tactic Engine for detailed line tactics →",
  "squad.noResult": "No preset tactic for this combination. Use the Anti-Tactic Engine for manual selection.",
  // WeeklyMeta
  "meta.badge": "Weekly Meta Tactic",
  "meta.winRate": "Win Rate",
  "meta.openEngine": "Open Anti-Tactic Engine",
  // PremiumTactics
  "premium.badge": "🔒 VIP Section",
  "premium.title1": "Premium",
  "premium.title2": "Tactics",
  "premium.desc": "Omer's personal VIP tactic collection for finals, cups and special matches.",
  "premium.active": "✓ Premium Active",
  "premium.exit": "Exit",
  "premium.unlockTitle": "Unlock VIP Tactics",
  "premium.unlockDesc": "Get full access to all exclusive tactics with premium membership. Enter your unique code after joining.",
  "premium.becomePremium": "💎 Go Premium",
  "premium.codeLabel": "Unlock with code",
  "premium.codePlaceholder": "Your premium code",
  "premium.unlock": "Unlock",
  "premium.wrongCode": "Wrong code. Try again.",
  "premium.required": "Premium Required",
  // DailyTactic
  "daily.openEngine": "Open Anti-Tactic Engine →",
  // Blog
  "blog.readMore": "Read More →",
  "blog.backToGuides": "← All Guides",
  "blog.tryCta": "Try all these tactics in the Anti-Tactic Engine!",
  "blog.openEngine": "Open Anti-Tactic Engine",
  // Navbar
  "nav.menu": "Menu",
  "nav.close": "Close",
  "nav.theme": "Theme",
  "nav.lang": "Language",
  // ManagerTools
  "tools.badge": "Manager Tools",
  "tools.title1": "Manager",
  "tools.title2": "Toolbox",
  "tools.tab.referee": "Referee Guide",
  "tools.tab.training": "Training",
  "tools.tab.transfer": "Transfer Guide",
  "tools.tab.league": "League Goal",
  "tools.tab.checklist": "Pre-Match",
  "tools.ref.title": "Referee Severity Guide",
  "tools.ref.desc": "Adjust your tackling style based on referee color. The warmer the color, the stricter the referee.",
  "tools.ref.advice": "Advice:",
  "tools.ref.tackling": "Recommended tackling:",
  "tools.train.title": "Camp / Training Advisor",
  "tools.train.desc": "Camp, training and hidden training recommendations by player age group.",
  "tools.train.years": "yrs",
  "tools.transfer.title": "Transfer Acquisition Guide",
  "tools.transfer.desc": "Select your formation and see what kind of players each position needs.",
  "tools.league.title": "League Goal Planner",
  "tools.league.desc": "Calculate how many wins you need to reach your target points.",
  "tools.league.total": "Total Matches",
  "tools.league.played": "Played",
  "tools.league.current": "Current Points",
  "tools.league.target": "Target Points",
  "tools.league.remaining": "Remaining Matches",
  "tools.league.needed": "Points Needed",
  "tools.league.wins": "Wins Needed",
  "tools.league.perMatch": "Avg Points / Match",
  "tools.league.reachable": "✅ Target is achievable",
  "tools.league.hard": "⚠️ Target is mathematically difficult",
  "tools.checklist.title": "Pre-Match Checklist",
  "tools.checklist.desc": "Check everything before kick-off.",
  // Hero CTA buttons
  "hero.findAntiTactic": "Find Anti-Tactic",
  "hero.quickSale": "Quick Sale Technique",
  "hero.support": "Support",
  // Manager mascot badge labels
  "hero.badge.winRate": "WIN RATE",
  "hero.badge.worldRank": "WORLD RANK",
  "hero.badge.matches": "MATCHES",
  "hero.badge.trophy": "TROPHY",
  "hero.badge.battlePoint": "BATTLE POINT",
  "hero.badge.experience": "EXPERIENCE",
});

// ── Data-layer translations: dynamic content updated on language switch ──
Object.assign(extraTranslations.en, {
  // Referee Severity Guide
  "ref.0.color": "Blue / Green", "ref.0.level": "Very Soft", "ref.0.meaning": "Referee rarely shows cards. Very tolerant of physical play.", "ref.0.advice": "Play hard, apply high press. Card risk is very low.", "ref.0.tackling": "Hard (High)",
  "ref.1.color": "Yellow", "ref.1.level": "Normal", "ref.1.meaning": "Balanced referee. No problems if you don't go overboard.", "ref.1.advice": "Play at normal intensity. Don't take unnecessary risks.", "ref.1.tackling": "Normal",
  "ref.2.color": "Orange", "ref.2.level": "Strict", "ref.2.meaning": "Quick to book. High card risk for physical challenges.", "ref.2.advice": "Lower intensity. Avoid yellow card accumulation.", "ref.2.tackling": "Soft (Low)",
  "ref.3.color": "Red", "ref.3.level": "Very Strict", "ref.3.meaning": "Most aggressive referee. Card risk even for minor fouls.", "ref.3.advice": "Play very softly. Minimize red card risk at all costs.", "ref.3.tackling": "Very Soft",
  // Training Advisor
  "train.0.ageGroup": "Young (17-21)", "train.0.camp": "Long camp (Development-focused)", "train.0.training": "Intensive individual training", "train.0.hidden": "Hidden training: ON (develops quickly)", "train.0.note": "Young players are the fastest developing group. Invest in them.",
  "train.1.ageGroup": "Prime (22-27)", "train.1.camp": "Medium camp (Balanced)", "train.1.training": "Position-based training", "train.1.hidden": "Hidden training: ON (balanced)", "train.1.note": "Peak efficiency period. Best performance + value balance here.",
  "train.2.ageGroup": "Experienced (28-31)", "train.2.camp": "Short camp (Form maintenance)", "train.2.training": "Light training", "train.2.hidden": "Hidden training: OFF (risky)", "train.2.note": "Development slowing down. Focus on maintaining form and fitness.",
  "train.3.ageGroup": "Veteran (32+)", "train.3.camp": "Very short camp", "train.3.training": "Conditioning only", "train.3.hidden": "Hidden training: OFF", "train.3.note": "Prepare the next generation. Don't tire veterans — let them play out their final seasons.",
  // Match Checklist
  "chk.0": "Study opponent's tactic and formation",
  "chk.1": "Choose anti-tactic based on home/away status",
  "chk.2": "Adjust Pressure / Style / Tempo values",
  "chk.3": "Check line tactics (Forwards / Midfield / Defence)",
  "chk.4": "Replace low-fitness players",
  "chk.5": "Check for injured or suspended players",
  "chk.6": "Adjust tackling based on referee color",
  "chk.7": "Make sure your best 11 are in the lineup",
  // Weekly Meta
  "meta.week": "5–11 Feb 2026", "meta.reason": "This week, 5-2-3 A counter-attack is performing very well in away matches.", "meta.winRateValue": "High",
  // Daily Tactics
  "dt.0.dayName": "Sunday", "dt.0.title": "Sunday Victory", "dt.0.style": "Wing Play", "dt.0.scenario": "When stronger at home", "dt.0.tip": "Use the home advantage in Sunday league matches. Attack down the wings, hold position in midfield.",
  "dt.1.dayName": "Monday", "dt.1.title": "Week Starter Counter", "dt.1.style": "Counter Attack", "dt.1.scenario": "When weaker away", "dt.1.tip": "Monday away matches are tough. Be patient with low pressure, strike with fast counters.",
  "dt.2.dayName": "Tuesday", "dt.2.title": "Tournament Tactic", "dt.2.style": "Counter Attack", "dt.2.scenario": "When squads are equal", "dt.2.tip": "Balance is crucial in Tuesday tournament matches. Progress safely with 5-2-3 counter.",
  "dt.3.dayName": "Wednesday", "dt.3.title": "Midfield Pressure", "dt.3.style": "Passing Game", "dt.3.scenario": "When equal at home", "dt.3.tip": "Dominate the midfield in Wednesday home matches. Wear the opponent down with passing, create positions.",
  "dt.4.dayName": "Thursday", "dt.4.title": "Away Warrior", "dt.4.style": "Counter Attack", "dt.4.scenario": "When equal away", "dt.4.tip": "Play defensively in Thursday away matches. Hold firm with 5-3-2, seek goals on the counter.",
  "dt.5.dayName": "Friday", "dt.5.title": "Friday Blitz", "dt.5.style": "Wing Play", "dt.5.scenario": "When stronger at home", "dt.5.tip": "Full throttle in Friday home matches! Suffocate the opponent with high tempo + high pressure.",
  "dt.6.dayName": "Saturday", "dt.6.title": "Weekend Derby", "dt.6.style": "Shoot on Sight", "dt.6.scenario": "In all situations", "dt.6.tip": "Shoot on Sight surprises in Saturday derbies. When the opponent expects attack, you counter instead.",
  // Opponent Tactic names (dropdown)
  "ot.433A.name": "4-3-3 A (Wing Play / Passing)", "ot.433B.name": "4-3-3 B (Wing Play / Passing)", "ot.442.name": "4-4-2 A/B (Passing Game)", "ot.4231.name": "4-2-3-1 (Shoot on Sight)", "ot.451.name": "4-5-1 (Shoot on Sight)",
  "ot.523.name": "5-2-3 A/B (Counter Attack)", "ot.541.name": "5-4-1 A/B (Shoot on Sight / Counter)", "ot.631.name": "6-3-1 A/B (Counter Attack)", "ot.532.name": "5-3-2 (Counter Attack)", "ot.5311.name": "5-3-1-1 (Counter Attack)",
  // Tactic style names for recommendedFormation localization
  "style.counterAttack": "Counter Attack", "style.wingPlay": "Wing Play", "style.passingGame": "Passing Game", "style.shootOnSight": "Shoot on Sight", "style.defensive": "Defensive", "style.bus": "Park Bus", "style.counter": "Counter", "style.wingPassing": "Wing/Passing",
  // Premium Tactics
  "vip.1.name": "VIP Final Tactic", "vip.1.scenario": "Special for Finals / Cup matches", "vip.1.note": "Special combination I use in top-level tournament finals. Push the wings to the limit.",
  "vip.2.name": "VIP Away Fortress", "vip.2.scenario": "Away against a strong opponent", "vip.2.note": "For taking points away against a very strong opponent. Fully compact, fast counter.",
  "vip.3.name": "VIP Comeback", "vip.3.scenario": "When trailing in a match (2nd half)", "vip.3.note": "Switch to this at halftime when trailing. Full attacking pressure.",
  // Squad Profiles (Transfer Guide)
  "sp.433.0.pos": "ST (Striker)", "sp.433.0.trait": "Speed + Finishing (High rating)", "sp.433.1.pos": "Wingers (MR/ML)", "sp.433.1.trait": "Speed + Dribbling", "sp.433.2.pos": "Midfield (MC)", "sp.433.2.trait": "Passing + Tackling balance", "sp.433.3.pos": "Defence (DC)", "sp.433.3.trait": "Positioning + Strength",
  "sp.523.0.pos": "ST", "sp.523.0.trait": "Speed (Critical for counter-attack)", "sp.523.1.pos": "Defenders (3x DC)", "sp.523.1.trait": "Strength + Positioning", "sp.523.2.pos": "MC", "sp.523.2.trait": "Tackling-focused", "sp.523.3.pos": "Winger (MR/ML)", "sp.523.3.trait": "Quick finisher",
  "sp.442.0.pos": "2x ST", "sp.442.0.trait": "One fast, one strong combination", "sp.442.1.pos": "Wingers", "sp.442.1.trait": "Crossing + fast", "sp.442.2.pos": "MC", "sp.442.2.trait": "Passing playmaker", "sp.442.3.pos": "Defence", "sp.442.3.trait": "Balanced positioning",
  "sp.451.0.pos": "ST", "sp.451.0.trait": "Long shots + strength (Shoot on Sight)", "sp.451.1.pos": "Midfield (5x)", "sp.451.1.trait": "Tackling + passing", "sp.451.2.pos": "Defence", "sp.451.2.trait": "Positioning-focused",
  // Changelog
  "cl.type.new": "New", "cl.type.update": "Update", "cl.type.meta": "Meta",
  "cl.0.title": "5-2-3 A Counter Meta Strengthened", "cl.0.desc": "5-2-3 A counter is more effective away after the latest engine update. Pressure values updated.",
  "cl.1.title": "Quick Sale & Today's Matches Added", "cl.1.desc": "Player sale calculator and live match prediction system added to the site.",
  "cl.2.title": "4-3-3 B Wing Tactic Revised", "cl.2.desc": "4-3-3 B style value optimized when stronger at home.",
  // CommunityHub
  "hub.emailBadge": "Stay Updated",
  "hub.emailTitle": "Be the first to hear about new tactics",
  "hub.emailDesc": "Leave your email and we'll notify you about new tactics and meta updates.",
  "hub.emailPlaceholder": "email@example.com",
  "hub.subscribe": "Subscribe",
  "hub.subscribeSuccess": "You're subscribed! Thank you.",
  "hub.emailInvalid": "Please enter a valid email address.",
  "hub.emailError": "Could not subscribe. Please try again.",
  "hub.youtubeCTA": "▶ Subscribe on YouTube",
  "hub.changelogBadge": "Update Log",
  "hub.changelogTitle": "OSM Next Level Log",
  // FAQ
  "faq.badge": "Questions & Answers",
  "faq.title": "OSM Frequently Asked Questions",
  "faq.q1": "What is the best OSM tactic for winning matches?",
  "faq.a1": "In OSM, the best tactic depends on your squad strength and match location. 4-3-3 Wing Play and 4-5-1 Shoot on Sight are consistently top-tier, but adapting your formation to the opponent's setup is what separates good managers from great ones.",
  "faq.q2": "How can I find a perfect counter-tactic in OSM?",
  "faq.a2": "Use our OSM Anti-Tactic Engine above. Select your opponent's formation and mentality, then the system instantly calculates the optimal counter-tactic based on real match data and tactical logic.",
  "faq.q3": "What are the best OSM advanced settings (sliders) for success?",
  "faq.a3": "For attacking formations, use high Pressure (60-80) and high Tempo. For defensive setups, drop Pressure to 30-50 and increase Positioning. Always match your Style slider to your formation's natural strength.",
  "faq.q4": "How do I improve my OSM squad value quickly?",
  "faq.a4": "Apply the OSM Quick Sale technique: identify underperforming players, sell them at optimal timing, and reinvest in young talent under 24. Young players develop faster and increase in market value significantly over a season.",
  "faq.q5": "Does match location influence OSM results?",
  "faq.a5": "Yes. Playing at home in OSM provides a hidden bonus to your squad's performance. Use a more offensive mentality and higher pressure at home, and a compact defensive approach away to maximize your points per match.",
});

Object.assign(extraTranslations.tr, {
  // Referee Severity Guide
  "ref.0.color": "Mavi / Yeşil", "ref.0.level": "Çok Yumuşak", "ref.0.meaning": "Hakem kart göstermeye çok meyilli değil. Sert oyuna toleranslı.", "ref.0.advice": "Sert oyna, presi yükselt. Kart riski düşük.", "ref.0.tackling": "Sert (Yüksek)",
  "ref.1.color": "Sarı", "ref.1.level": "Normal", "ref.1.meaning": "Dengeli hakem. Aşırıya kaçmazsan sorun çıkmaz.", "ref.1.advice": "Normal sertlikte oyna. Gereksiz risk alma.", "ref.1.tackling": "Normal",
  "ref.2.color": "Turuncu", "ref.2.level": "Sert", "ref.2.meaning": "Kolay kart çıkarır. Sert müdahalelerde kart riski yüksek.", "ref.2.advice": "Sertliği düşür. Kart cezalısı kalmamaya dikkat et.", "ref.2.tackling": "Yumuşak (Düşük)",
  "ref.3.color": "Kırmızı", "ref.3.level": "Çok Sert", "ref.3.meaning": "En agresif hakem. En ufak faulde kart riski var.", "ref.3.advice": "Çok yumuşak oyna. Kırmızı kart riskini minimuma indir.", "ref.3.tackling": "Çok Yumuşak",
  // Training Advisor
  "train.0.ageGroup": "Genç (17-21)", "train.0.camp": "Uzun kamp (Gelişim odaklı)", "train.0.training": "Yoğun bireysel antrenman", "train.0.hidden": "Gizli antrenman: AÇIK (hızlı gelişir)", "train.0.note": "Genç oyuncular en hızlı gelişen gruptur. Yatırım yap.",
  "train.1.ageGroup": "Olgun (22-27)", "train.1.camp": "Orta kamp (Denge)", "train.1.training": "Mevki bazlı antrenman", "train.1.hidden": "Gizli antrenman: AÇIK (dengeli)", "train.1.note": "En verimli dönem. Performans + değer dengesi en iyi burada.",
  "train.2.ageGroup": "Tecrübeli (28-31)", "train.2.camp": "Kısa kamp (Form koruma)", "train.2.training": "Hafif antrenman", "train.2.hidden": "Gizli antrenman: KAPALI (riskli)", "train.2.note": "Gelişim yavaşladı. Form ve kondisyonu korumaya odaklan.",
  "train.3.ageGroup": "Veteran (32+)", "train.3.camp": "Çok kısa kamp", "train.3.training": "Sadece kondisyon", "train.3.hidden": "Gizli antrenman: KAPALI", "train.3.note": "Yeni nesil hazırla. Veteranı yorma, son sezonlarını oynat.",
  // Match Checklist
  "chk.0": "Rakibin taktiğini ve dizilişini incele",
  "chk.1": "Ev / Deplasman durumuna göre anti-taktik seç",
  "chk.2": "Baskı / Stil / Tempo değerlerini ayarla",
  "chk.3": "Çizgi taktiklerini (Forvet/Orta/Defans) kontrol et",
  "chk.4": "Kondisyon düşük oyuncuları değiştir",
  "chk.5": "Sakat veya kart cezalı oyuncu var mı bak",
  "chk.6": "Hakem rengine göre sertliği ayarla",
  "chk.7": "En iyi 11'i sahaya sürdüğünden emin ol",
  // Weekly Meta
  "meta.week": "5-11 Şubat 2026", "meta.reason": "Bu hafta deplasman maçlarında 5-2-3 A kontra çok iyi tutuyor.", "meta.winRateValue": "Yüksek",
  // Daily Tactics
  "dt.0.dayName": "Pazar", "dt.0.title": "Pazar Galibiyeti", "dt.0.style": "Kanatları Kullan", "dt.0.scenario": "Evde güçlüyken", "dt.0.tip": "Pazar günü lig maçlarında ev avantajını kullan. Kanatlardan yüklen, orta sahada pozisyon koru.",
  "dt.1.dayName": "Pazartesi", "dt.1.title": "Hafta Başı Kontra", "dt.1.style": "Kontra Atak", "dt.1.scenario": "Deplasmanda zayıfken", "dt.1.tip": "Hafta başı deplasman maçları zordur. Düşük baskıyla sabırlı bekle, hızlı kontralarla vur.",
  "dt.2.dayName": "Salı", "dt.2.title": "Turnuva Taktiği", "dt.2.style": "Kontra Atak", "dt.2.scenario": "Eşit kadroda", "dt.2.tip": "Salı turnuva maçlarında denge çok önemli. 5-2-3 kontra ile risksiz ilerle.",
  "dt.3.dayName": "Çarşamba", "dt.3.title": "Orta Saha Baskısı", "dt.3.style": "Paslı Oyun", "dt.3.scenario": "Evde eşitken", "dt.3.tip": "Çarşamba ev maçlarında orta sahayı domine et. Pas oyunuyla rakibi yor, pozisyon bul.",
  "dt.4.dayName": "Perşembe", "dt.4.title": "Deplasman Savaşçısı", "dt.4.style": "Kontra Atak", "dt.4.scenario": "Deplasmanda eşitken", "dt.4.tip": "Perşembe deplasman maçlarında defansif oyna. 5-3-2 ile sağlam dur, kontradan gol ara.",
  "dt.5.dayName": "Cuma", "dt.5.title": "Cuma Hücumu", "dt.5.style": "Kanatları Kullan", "dt.5.scenario": "Evde güçlüyken", "dt.5.tip": "Cuma ev maçlarında tam gaz! Yüksek tempo + yüksek baskı ile rakibi boğ.",
  "dt.6.dayName": "Cumartesi", "dt.6.title": "Hafta Sonu Derbisi", "dt.6.style": "Kaleyi Görünce Vur", "dt.6.scenario": "Her durumda", "dt.6.tip": "Cumartesi derbilerde KGV taktiği şaşırtır. Rakip hücum bekliyorsa sen kontradan geçersin.",
  // Opponent Tactic names
  "ot.433A.name": "4-3-3 A (Kanat / Pas)", "ot.433B.name": "4-3-3 B (Kanat / Pas)", "ot.442.name": "4-4-2 A/B (Paslı Oyun)", "ot.4231.name": "4-2-3-1 (Kaleye Vur)", "ot.451.name": "4-5-1 (Kaleye Vur)",
  "ot.523.name": "5-2-3 A/B (Kontra Atak)", "ot.541.name": "5-4-1 A/B (Kaleye Vur / Kontra)", "ot.631.name": "6-3-1 A/B (Kontra Atak)", "ot.532.name": "5-3-2 (Kontra Atak)", "ot.5311.name": "5-3-1-1 (Kontra Atak)",
  // Tactic style names
  "style.counterAttack": "Kontra Atak", "style.wingPlay": "Kanatları Kullan", "style.passingGame": "Paslı Oyun", "style.shootOnSight": "Kaleyi Görünce Vur", "style.defensive": "Defansif", "style.bus": "Otobüs", "style.counter": "Kontra", "style.wingPassing": "Kanat/Pas",
  // Premium Tactics
  "vip.1.name": "VIP Final Taktiği", "vip.1.scenario": "Final / Kupa maçları için özel", "vip.1.note": "Üst düzey turnuva finallerinde kullandığım özel kombinasyon. Kanatları sonuna kadar kullan.",
  "vip.2.name": "VIP Deplasman Kalesi", "vip.2.scenario": "Güçlü rakibe deplasmanda", "vip.2.note": "Çok güçlü rakibe deplasmanda puan almak için. Tam kapanıp hızlı kontra.",
  "vip.3.name": "VIP Geri Dönüş", "vip.3.scenario": "Maçta geride kalınca (2. yarı)", "vip.3.note": "Geriye düştüğünde devre arası buna geç. Tam hücum baskısı.",
  // Squad Profiles
  "sp.433.0.pos": "ST (Santrafor)", "sp.433.0.trait": "Hız + Bitiricilik (Yüksek puan)", "sp.433.1.pos": "Kanatlar (MR/ML)", "sp.433.1.trait": "Hız + Dribbling", "sp.433.2.pos": "Orta Saha (MC)", "sp.433.2.trait": "Pas + Top kapma dengesi", "sp.433.3.pos": "Defans (DC)", "sp.433.3.trait": "Pozisyon + Güç",
  "sp.523.0.pos": "ST", "sp.523.0.trait": "Hız (Kontra için kritik)", "sp.523.1.pos": "Stoperler (3x DC)", "sp.523.1.trait": "Güç + Pozisyon", "sp.523.2.pos": "MC", "sp.523.2.trait": "Top kapma odaklı", "sp.523.3.pos": "Kanat (MR/ML)", "sp.523.3.trait": "Hızlı bitirici",
  "sp.442.0.pos": "2x ST", "sp.442.0.trait": "Biri hızlı, biri güçlü kombinasyon", "sp.442.1.pos": "Kanatlar", "sp.442.1.trait": "Orta yapan + hızlı", "sp.442.2.pos": "MC", "sp.442.2.trait": "Pas dağıtan oyun kurucu", "sp.442.3.pos": "Defans", "sp.442.3.trait": "Dengeli pozisyon",
  "sp.451.0.pos": "ST", "sp.451.0.trait": "Uzaktan şut + güç (KGvV)", "sp.451.1.pos": "Orta Saha (5x)", "sp.451.1.trait": "Top kapma + pas", "sp.451.2.pos": "Defans", "sp.451.2.trait": "Pozisyon odaklı",
  // Changelog
  "cl.type.new": "Yeni", "cl.type.update": "Güncelleme", "cl.type.meta": "Meta",
  "cl.0.title": "5-2-3 A Kontra metası güçlendi", "cl.0.desc": "Son motor güncellemesinde 5-2-3 A kontra deplasmanda daha etkili. Baskı değerlerini güncelledim.",
  "cl.1.title": "Hızlı Satış ve Günün Maçları eklendi", "cl.1.desc": "Siteye oyuncu satış hesaplayıcı ve canlı maç tahmin sistemi eklendi.",
  "cl.2.title": "4-3-3 B kanat taktiği revize edildi", "cl.2.desc": "Evde güçlüyken 4-3-3 B stil değeri optimize edildi.",
  // CommunityHub
  "hub.emailBadge": "Haberdar Ol",
  "hub.emailTitle": "Yeni taktiklerden ilk sen haberdar ol",
  "hub.emailDesc": "Email bırak, yeni taktik ve meta güncellemelerinde haber verelim.",
  "hub.emailPlaceholder": "email@ornek.com",
  "hub.subscribe": "Kaydol",
  "hub.subscribeSuccess": "Kaydoldun! Teşekkürler.",
  "hub.emailInvalid": "Geçerli bir email gir.",
  "hub.emailError": "Kayıt yapılamadı. Lütfen tekrar dene.",
  "hub.youtubeCTA": "▶ YouTube Abone Ol",
  "hub.changelogBadge": "Güncelleme Günlüğü",
  "hub.changelogTitle": "OSM Next Level Günlüğü",
  // FAQ
  "faq.badge": "Soru & Cevap",
  "faq.title": "OSM Sıkça Sorulan Sorular",
  "faq.q1": "OSM'de maç kazanmak için en iyi taktik nedir?",
  "faq.a1": "OSM'de en iyi taktik kadro gücüne ve maç konumuna göre değişir. 4-3-3 Kanat Oyunu ve 4-5-1 Kaleyi Görünce Vur sürekli üst düzey seçenekler arasındadır; ancak rakibin dizilişine göre adaptasyon, iyi menajerleri büyük menajerlere dönüştüren şeydir.",
  "faq.q2": "OSM'de mükemmel bir karşı taktik nasıl bulunur?",
  "faq.a2": "Yukarıdaki OSM Anti-Taktik Motorunu kullan. Rakibinin formasyonunu ve zihniyetini seç, sistem gerçek maç verilerine ve taktik mantığa dayanarak anında optimal karşı taktiği hesaplar.",
  "faq.q3": "OSM'de başarı için en iyi gelişmiş ayarlar (kaydırıcılar) nelerdir?",
  "faq.a3": "Saldırgan dizilişler için yüksek Baskı (60-80) ve yüksek Tempo kullan. Defansif düzenler için Baskıyı 30-50'ye düşür ve Konumlanmayı artır. Stil kaydırıcısını her zaman formasyonunun doğal gücüyle eşleştir.",
  "faq.q4": "OSM kadro değerimi hızlıca nasıl artırırım?",
  "faq.a4": "OSM Hızlı Satış tekniğini uygula: düşük performanslı oyuncuları tespit et, optimal zamanda sat ve 24 yaş altı genç yeteneklere yatırım yap. Genç oyuncular daha hızlı gelişir ve sezon boyunca piyasa değerleri önemli ölçüde artar.",
  "faq.q5": "Maç konumu OSM sonuçlarını etkiler mi?",
  "faq.a5": "Evet. OSM'de evde oynamak kadronun performansına gizli bir bonus sağlar. Maç başına puanını en üst düzeye çıkarmak için evde daha saldırgan bir zihniyet ve yüksek baskı, deplasmanda ise kompakt defansif bir yaklaşım kullan.",
});

// Diğer dillere özel çeviriler (en'i miras al, üstüne ekle)
extraTranslations.hu = {
  ...extraTranslations.en,
  ...extraTranslations.hu,
  "nav.donate": "Támogass",
  "nav.login": "Belépés",
  "nav.signup": "Regisztráció",
  "nav.profile": "Profilom",
  "nav.leaderboard": "Ranglista",
  "profile.modalTitle": "Belépés / Regisztráció",
};
extraTranslations.ar = {
  ...extraTranslations.en,
  ...extraTranslations.ar,
  "nav.donate": "ادعمنا",
  "nav.login": "تسجيل دخول",
  "nav.signup": "إنشاء حساب",
  "nav.profile": "ملفي",
  "nav.leaderboard": "المتصدرون",
  "profile.modalTitle": "تسجيل دخول / إنشاء حساب",
};
extraTranslations.pt = {
  ...extraTranslations.en,
  ...extraTranslations.pt,
  "nav.donate": "Apoiar",
  "nav.login": "Entrar",
  "nav.signup": "Registar",
  "nav.profile": "Meu Perfil",
  "nav.leaderboard": "Classificação",
  "profile.modalTitle": "Entrar / Registar",
};

// Arabic-specific overrides: directional strings (no arrows), localized squad/meta/premium keys
Object.assign(extraTranslations.ar, {
  "blog.readMore": "اقرأ المزيد",
  "blog.backToGuides": "جميع الأدلة →",
  "blog.openEngine": "افتح محرك التكتيك المضاد",
  "blog.tryCta": "جرب جميع هذه التكتيكات في محرك التكتيك المضاد!",
  "squad.badge": "أداة تحليل الفريق",
  "squad.title1": "قيمة",
  "squad.title2": "الفريق",
  "squad.desc": "أدخل قيمة فريقك وقيمة الخصم. يحسب النظام توازن القوى ويوصي بأفضل تكتيك مضاد.",
  "squad.myValue": "قيمة فريقك",
  "squad.oppValue": "قيمة فريق الخصم",
  "squad.oppTactic": "تكتيك الخصم",
  "squad.strength": "توازن القوى",
  "squad.stronger": "أنت الأقوى ⭐",
  "squad.equal": "متكافئون ⚖️",
  "squad.weaker": "أنت الأضعف ⚠️",
  "squad.recommended": "التكتيك المضاد الموصى به",
  "squad.openEngine": "افتح محرك التكتيك المضاد",
  "squad.noResult": "لا يوجد تكتيك محدد مسبقاً لهذا التوليف. استخدم محرك التكتيك المضاد.",
  "meta.badge": "أفضل تكتيك هذا الأسبوع",
  "meta.winRate": "معدل الفوز",
  "meta.openEngine": "افتح محرك التكتيك المضاد",
  "daily.openEngine": "افتح محرك التكتيك المضاد",
  "premium.badge": "🔒 قسم VIP",
  "premium.title2": "التكتيكات",
  "premium.active": "✓ Premium نشط",
  "premium.exit": "خروج",
  "premium.unlockTitle": "افتح تكتيكات VIP",
  "premium.unlock": "فتح",
  "premium.wrongCode": "رمز خاطئ. حاول مرة أخرى.",
  "premium.required": "يلزم Premium",
  "tools.badge": "أدوات المدير",
  "tools.title1": "مجموعة أدوات",
  "tools.title2": "المدير",
  "tools.tab.referee": "دليل الحكم",
  "tools.tab.training": "التدريب",
  "tools.tab.transfer": "دليل النقل",
  "tools.tab.league": "هدف الدوري",
  "tools.tab.checklist": "قبل المباراة",
  "nav.menu": "القائمة",
  "nav.close": "إغلاق",
  "nav.theme": "السمة",
  "nav.lang": "اللغة",
  // Referee — Arabic
  "ref.0.color": "أزرق / أخضر", "ref.0.level": "لين جداً", "ref.0.meaning": "الحكم نادراً ما يُصدر بطاقات. متسامح جداً مع اللعب الصارم.", "ref.0.advice": "العب بصرامة، ارفع الضغط. خطر البطاقات منخفض جداً.", "ref.0.tackling": "صارم (مرتفع)",
  "ref.1.color": "أصفر", "ref.1.level": "عادي", "ref.1.meaning": "حكم متوازن. لا مشاكل إذا لم تبالغ.", "ref.1.advice": "العب بشدة طبيعية. لا تتخذ مخاطر غير ضرورية.", "ref.1.tackling": "عادي",
  "ref.2.color": "برتقالي", "ref.2.level": "صارم", "ref.2.meaning": "سريع في إصدار البطاقات. خطر بطاقات عالٍ على التدخلات الصارمة.", "ref.2.advice": "اخفض الشدة. تجنب تراكم البطاقات الصفراء.", "ref.2.tackling": "ناعم (منخفض)",
  "ref.3.color": "أحمر", "ref.3.level": "صارم جداً", "ref.3.meaning": "الحكم الأكثر عدوانية. خطر البطاقات حتى للمخالفات الطفيفة.", "ref.3.advice": "العب بنعومة شديدة. قلل خطر البطاقة الحمراء إلى أدنى مستوى.", "ref.3.tackling": "ناعم جداً",
  // Match Checklist — Arabic
  "chk.0": "ادرس تكتيك الخصم وتشكيلته", "chk.1": "اختر التكتيك المضاد بناءً على وضع الملعب", "chk.2": "اضبط قيم الضغط / الأسلوب / الإيقاع",
  "chk.3": "تحقق من تكتيكات الخطوط (الهجوم / الوسط / الدفاع)", "chk.4": "استبدل اللاعبين ضعيفي اللياقة",
  "chk.5": "تحقق من وجود لاعبين مصابين أو موقوفين", "chk.6": "اضبط قوة التدخل بناءً على لون الحكم", "chk.7": "تأكد من أن أفضل 11 لاعب في التشكيلة",
  // Weekly Meta — Arabic
  "meta.week": "5-11 فبراير 2026", "meta.reason": "هذا الأسبوع، يؤدي هجوم الارتداد 5-2-3 أداءً ممتازاً في مباريات الخارج.", "meta.winRateValue": "مرتفع",
  // Opponent tactics — Arabic
  "ot.433A.name": "4-3-3 A (جناح/تمرير)", "ot.433B.name": "4-3-3 B (جناح/تمرير)", "ot.442.name": "4-4-2 (لعب بالتمرير)", "ot.4231.name": "4-2-3-1 (تسديد مباشر)", "ot.451.name": "4-5-1 (تسديد مباشر)",
  "ot.523.name": "5-2-3 A/B (ارتداد)", "ot.541.name": "5-4-1 A/B (تسديد/ارتداد)", "ot.631.name": "6-3-1 A/B (ارتداد)", "ot.532.name": "5-3-2 (ارتداد)", "ot.5311.name": "5-3-1-1 (ارتداد)",
  // Style names — Arabic
  "style.counterAttack": "هجوم ارتداد", "style.wingPlay": "لعب الأجنحة", "style.passingGame": "لعب التمرير", "style.shootOnSight": "التسديد عند الرؤية", "style.defensive": "دفاعي", "style.bus": "الحافلة", "style.counter": "ارتداد", "style.wingPassing": "جناح/تمرير",
  // Daily Tactics — Arabic
  "dt.0.dayName": "الأحد", "dt.0.title": "انتصار الأحد", "dt.0.style": "لعب الأجنحة", "dt.0.scenario": "عند التفوق في الملعب", "dt.0.tip": "استغل ميزة الملعب. هاجم من الأجنحة، حافظ على المواقع في الوسط.",
  "dt.1.dayName": "الاثنين", "dt.1.title": "ارتداد بداية الأسبوع", "dt.1.style": "هجوم ارتداد", "dt.1.scenario": "عند الضعف في الخارج", "dt.1.tip": "مباريات الخارج يوم الاثنين صعبة. كن صبوراً بضغط منخفض، واضرب بارتدادات سريعة.",
  "dt.2.dayName": "الثلاثاء", "dt.2.title": "تكتيك البطولة", "dt.2.style": "هجوم ارتداد", "dt.2.scenario": "عند التكافؤ", "dt.2.tip": "التوازن مهم جداً في مباريات بطولة الثلاثاء. تقدم بأمان مع ارتداد 5-2-3.",
  "dt.3.dayName": "الأربعاء", "dt.3.title": "ضغط الوسط", "dt.3.style": "لعب التمرير", "dt.3.scenario": "عند التكافؤ في الملعب", "dt.3.tip": "سيطر على الوسط. أتعب الخصم بالتمرير، ابحث عن المواقع.",
  "dt.4.dayName": "الخميس", "dt.4.title": "محارب الخارج", "dt.4.style": "هجوم ارتداد", "dt.4.scenario": "عند التكافؤ في الخارج", "dt.4.tip": "العب دفاعياً. تمسك بـ5-3-2، ابحث عن الأهداف في الارتداد.",
  "dt.5.dayName": "الجمعة", "dt.5.title": "هجوم الجمعة", "dt.5.style": "لعب الأجنحة", "dt.5.scenario": "عند التفوق في الملعب", "dt.5.tip": "بكل قوة! اخنق الخصم بإيقاع عالٍ + ضغط عالٍ.",
  "dt.6.dayName": "السبت", "dt.6.title": "ديربي نهاية الأسبوع", "dt.6.style": "التسديد عند الرؤية", "dt.6.scenario": "في جميع الحالات", "dt.6.tip": "التسديد المباشر يفاجئ في ديربي السبت. عندما يتوقع الخصم الهجوم، تعاكس بالارتداد.",
  // Premium Tactics — Arabic
  "vip.1.name": "تكتيك VIP النهائي", "vip.1.scenario": "خاص للنهائيات / مباريات الكأس", "vip.1.note": "مزيج خاص للنهائيات. ادفع الأجنحة إلى الحد الأقصى.",
  "vip.2.name": "حصن VIP بعيداً", "vip.2.scenario": "بعيداً ضد خصم قوي", "vip.2.note": "لأخذ النقاط بعيداً ضد خصم قوي جداً. انغلق بالكامل، ارتداد سريع.",
  "vip.3.name": "عودة VIP", "vip.3.scenario": "عند التأخر في المباراة (الشوط الثاني)", "vip.3.note": "انتقل إلى هذا في استراحة الشوط عند التأخر. ضغط هجومي كامل.",
  // FAQ — Arabic
  "faq.badge": "أسئلة وأجوبة",
  "faq.title": "الأسئلة الشائعة حول OSM",
  "faq.q1": "ما هو أفضل تكتيك OSM للفوز بالمباريات؟",
  "faq.a1": "في OSM، يعتمد أفضل تكتيك على قوة فريقك وموقع المباراة. 4-3-3 لعب الأجنحة و4-5-1 التسديد المباشر خياران متميزان باستمرار، لكن التكيف مع تشكيلة الخصم هو ما يميز المديرين الجيدين عن العظماء.",
  "faq.q2": "كيف يمكنني إيجاد تكتيك مضاد مثالي في OSM؟",
  "faq.a2": "استخدم محرك التكتيك المضاد OSM أعلاه. حدد تشكيلة خصمك وأسلوبه، يحسب النظام فوراً التكتيك المضاد الأمثل استناداً إلى بيانات المباريات الحقيقية والمنطق التكتيكي.",
  "faq.q3": "ما هي أفضل الإعدادات المتقدمة في OSM للنجاح؟",
  "faq.a3": "للتشكيلات الهجومية، استخدم ضغطاً عالياً (60-80) وإيقاعاً عالياً. للأنظمة الدفاعية، اخفض الضغط إلى 30-50 وزد التمركز. اضبط دائماً شريط الأسلوب ليتوافق مع قوة تشكيلتك الطبيعية.",
  "faq.q4": "كيف أحسّن قيمة فريقي في OSM بسرعة؟",
  "faq.a4": "طبّق تقنية البيع السريع في OSM: حدد اللاعبين ضعيفي الأداء، بعهم في الوقت المثالي، وأعد الاستثمار في المواهب الشابة دون 24 عاماً. يتطور الشباب بسرعة أكبر وترتفع قيمتهم السوقية بشكل ملحوظ خلال الموسم.",
  "faq.q5": "هل يؤثر موقع المباراة على نتائج OSM؟",
  "faq.a5": "نعم. اللعب في الملعب الرئيسي في OSM يمنح أداء فريقك مكافأة خفية. استخدم أسلوباً هجومياً أكثر وضغطاً أعلى في الملعب، ونهجاً دفاعياً مضغوطاً خارجه لتعظيم نقاطك لكل مباراة.",
});

Object.assign(extraTranslations.pt, {
  // FAQ — Portuguese
  "faq.badge": "Perguntas e Respostas",
  "faq.title": "Perguntas Frequentes sobre OSM",
  "faq.q1": "Qual é a melhor tática OSM para ganhar partidas?",
  "faq.a1": "No OSM, a melhor tática depende da força do seu elenco e do local da partida. 4-3-3 Jogo de Alas e 4-5-1 Chute Direto são consistentemente as melhores escolhas, mas adaptar sua formação à configuração do adversário é o que separa os bons gestores dos grandes.",
  "faq.q2": "Como posso encontrar um contra-tática perfeito no OSM?",
  "faq.a2": "Use o Motor Anti-Tática OSM acima. Selecione a formação e a mentalidade do adversário, e o sistema calcula instantaneamente o contra-tática ideal com base em dados de partidas reais e lógica tática.",
  "faq.q3": "Quais são as melhores configurações avançadas do OSM para ter sucesso?",
  "faq.a3": "Para formações de ataque, use Pressão alta (60-80) e Ritmo alto. Para configurações defensivas, reduza a Pressão para 30-50 e aumente o Posicionamento. Alinhe sempre o controle de Estilo com a força natural da sua formação.",
  "faq.q4": "Como melhorar rapidamente o valor do meu elenco OSM?",
  "faq.a4": "Aplique a técnica de Venda Rápida do OSM: identifique jogadores com baixo rendimento, venda-os no momento ideal e reinvista em jovens talentos com menos de 24 anos. Os jovens se desenvolvem mais rápido e aumentam significativamente o valor de mercado ao longo de uma temporada.",
  "faq.q5": "A localização da partida influencia os resultados no OSM?",
  "faq.a5": "Sim. Jogar em casa no OSM oferece um bônus oculto ao desempenho do seu elenco. Use uma mentalidade mais ofensiva e maior pressão em casa, e uma abordagem defensiva compacta fora para maximizar seus pontos por partida.",
});

Object.assign(extraTranslations.en, {
  // Anti-Tactic Finder additional UI
  "anti.matchLocation": "MATCH LOCATION",
  "anti.homeMatch": "HOME MATCH",
  "anti.oppTactic": "OPPONENT TACTIC",
  "anti.counterLabel": "Counter:",
  "anti.squadStrength": "SQUAD STRENGTH",
  "anti.strongerBtn": "STRONGER",
  "anti.equalBtn": "EQUAL",
  "anti.weakerBtn": "WEAKER",
  "anti.recommended": "RECOMMENDED ANTI-TACTIC",
  "anti.yourCounter": "YOUR COUNTER",
  "anti.masterHome": "⭐ MASTER HOME META",
  "anti.masterAway": "⭐ MASTER AWAY META",
  "anti.badgeElite": "ELITE / MUST-USE",
  "anti.badgeSolid": "SOLID / RELIABLE",
  "anti.badgeSit": "SITUATIONAL",
  "anti.gamePlan": "GAME PLAN",
  "anti.oppPlays": "OPPONENT PLAYS",
  "anti.optA": "Option A",
  "anti.optADefault": "Default",
  "anti.optB": "Option B",
  "anti.optBAlt": "Alt",
  "anti.successRate": "SUCCESS RATE",
  "anti.offsideTrap": "OFFSIDE TRAP",
  "anti.highValueAlt": "HIGH-VALUE ALTERNATIVE",
  "anti.locHome": "Home",
  "anti.locAway": "Away",
  "anti.strStronger": "Stronger",
  "anti.strEqual": "Equal",
  "anti.strWeaker": "Weaker",
  // Mentality labels — used in Step 2 list and game-plan display
  "mentality.wingPlay":      "Wing Play",
  "mentality.passingGame":   "Passing Game",
  "mentality.shootOnSight":  "Shoot on Sight",
  "mentality.counterAttack": "Counter Attack",
  "mentality.longBall":      "Long Ball",
  // Alternative tactic card (HomeTacticHero)
  "alternative.title":   "HIGH VALUE ALTERNATIVE TACTIC",
  "alternative.desc":    "Our consistently used custom home tactic configuration against any opponent formation.",
  "alternative.winRate": "WIN RATE 95%",
  "anti.tacticsToday": "Tactics Generated Today",
  // Events Schedule
  "events.badge": "SPECIAL EVENTS",
  "events.schedule": "Schedule",
  "events.autoUpdate": "Auto-updates in real time · UK timezone",
  "events.pill.active": "● Event Active Now",
  "events.pill.remaining": "{n} events remaining",
  "events.badge.live": "● LIVE",
  "events.badge.upcoming": "UPCOMING",
  "events.badge.ended": "ENDED",
  "events.disclaimer": "Auto-updates in real time · UK timezone",
  "events.status.finished": "ENDED",
  "events.status.upcoming": "UPCOMING",
  "ev.0.name": "Extreme Training",
  "ev.0.mechanic": "Faster training: 2H normal, 1:30H Universal",
  "ev.1.name": "Transfer Madness",
  "ev.1.mechanic": "6 players on list, 2H Scout",
  "ev.2.name": "Guaranteed Training Boost",
  "ev.2.mechanic": "No normal trainings — Faster training: 4H / 3H",
  "ev.3.name": "Golden Oldies × Legends",
  "ev.3.mechanic": "Old players progression, Legends on list",
  "ev.4.name": "Booming Stadium",
  "ev.4.mechanic": "4H Stadium timers",
  "ev.5.name": "Training Talents",
  "ev.5.mechanic": "Younger players progression",
  "ev.6.name": "Legends",
  "ev.6.mechanic": "Legends on Transfer List",
  "ev.7.name": "Superfast Trainer",
  "ev.7.mechanic": "2H normal trainers, 1H Universal Trainer",
  "ev.8.name": "Intense Friendlies",
  "ev.8.mechanic": "Extra progression with Friendlies",
  // Stats + disclaimer
  "stats.world": "WORLD NO. 1 LEGACY",
  "disclaimer.coach_label": "COACH'S WARNING",
  // Formation styles
  "style.counter_attack": "Counter Attack",
  "style.wing_play": "Wing Play",
  "style.shoot_on_sight": "Shoot on Sight",
  "style.passing_game": "Passing Game",
  // Month names (full)
  "months.january": "January", "months.february": "February", "months.march": "March",
  "months.april": "April", "months.may": "May", "months.june": "June",
  "months.july": "July", "months.august": "August", "months.september": "September",
  "months.october": "October", "months.november": "November", "months.december": "December",
  // Events header
  "events.program_title": "Program",
  // Tactical engine interactive labels
  "tactical.step1": "Step 1: Venue",
  "tactical.step2": "Step 2: Opponent Tactic",
  "tactical.step3": "Step 3: Squad Strength",
  "tactical.home": "HOME",
  "tactical.away": "AWAY",
  "tactical.stronger": "STRONGER",
  "tactical.equal": "EQUAL",
  "tactical.weaker": "WEAKER",
  // Football pitch line-tactics labels
  "pitch.lineTactics": "LINE TACTICS",
  "pitch.attackOnly": "Attack Only",
  "pitch.protectDefense": "Protect the Defense",
  "pitch.stayBack": "Stay Back",
  "pitch.defendDeep": "Defend Deep",
  "pitch.zoneMarking": "Zone Marking",
  "pitch.manMarking": "Man Marking",
  "pitch.offsideNo": "Offside Trap: No",
  "pitch.offsideYes": "Offside Trap: Yes",
});

Object.assign(extraTranslations.tr, {
  // Anti-Tactic Finder additional UI
  "anti.matchLocation": "MAÇ KONUMU",
  "anti.homeMatch": "EV MAÇI",
  "anti.oppTactic": "RAKİP TAKTİĞİ",
  "anti.counterLabel": "Karşı:",
  "anti.squadStrength": "KADRO GÜCÜ",
  "anti.strongerBtn": "GÜÇLÜ",
  "anti.equalBtn": "EŞİT",
  "anti.weakerBtn": "ZAYIF",
  "anti.recommended": "ÖNERİLEN ANTI-TAKTİK",
  "anti.yourCounter": "SENİN KARŞI TAKTİĞİN",
  "anti.masterHome": "⭐ EV META'SINI YÖNET",
  "anti.masterAway": "⭐ DEPLASMAN META'SINI YÖNET",
  "anti.badgeElite": "ELİT / MUTLAKA KULLAN",
  "anti.badgeSolid": "SAĞLAM / GÜVENİLİR",
  "anti.badgeSit": "DURUMA GÖRE",
  "anti.gamePlan": "OYUN PLANI",
  "anti.oppPlays": "RAKİP KULLANIR",
  "anti.optA": "Seçenek A",
  "anti.optADefault": "Varsayılan",
  "anti.optB": "Seçenek B",
  "anti.optBAlt": "Alternatif",
  "anti.successRate": "BAŞARI ORANI",
  "anti.offsideTrap": "OFSAYt TUZAĞI",
  "anti.highValueAlt": "YÜKSEK DEĞERLİ ALTERNATİF",
  "anti.locHome": "Ev",
  "anti.locAway": "Deplasman",
  "anti.strStronger": "Güçlü",
  "anti.strEqual": "Eşit",
  "anti.strWeaker": "Zayıf",
  "mentality.wingPlay":      "Kanatları Kullan",
  "mentality.passingGame":   "Paslaşarak Oyun",
  "mentality.shootOnSight":  "Kaleyi Görünce Vur",
  "mentality.counterAttack": "Kontra Atak",
  "mentality.longBall":      "Uzun Top",
  "alternative.title":   "YÜKSEK DEĞERLİ ALTERNATİF TAKTİK",
  "alternative.desc":    "Evimizde her dizilişe karşı sürekli kullandığımız özel taktik konfigürasyonu.",
  "alternative.winRate": "KAZANMA ORANI %95",
  "anti.tacticsToday": "Bugün Üretilen Taktik",
  // Events Schedule
  "events.badge": "ÖZEL ETKİNLİKLER",
  "events.schedule": "Program",
  "events.autoUpdate": "Gerçek zamanlı güncellenir · İngiltere saati",
  "events.pill.active": "● Aktif Etkinlik",
  "events.pill.remaining": "{n} etkinlik kaldı",
  "events.badge.live": "● CANLI",
  "events.badge.upcoming": "YAKINDA",
  "events.badge.ended": "BİTTİ",
  "events.disclaimer": "Gerçek zamanlı güncellenir · İngiltere saati",
  "events.status.finished": "BİTTİ",
  "events.status.upcoming": "YAKINDA",
  "ev.0.name": "Yoğun Antrenman",
  "ev.0.mechanic": "Hızlı antrenman: Normal 2S, Evrensel 1:30S",
  "ev.1.name": "Transfer Çılgınlığı",
  "ev.1.mechanic": "Listede 6 oyuncu, 2S İzci",
  "ev.2.name": "Garantili Antrenman Artışı",
  "ev.2.mechanic": "Normal antrenman yok — Hızlı antrenman: 4S / 3S",
  "ev.3.name": "Eski Yıldızlar × Efsaneler",
  "ev.3.mechanic": "Yaşlı oyuncu gelişimi, listede Efsaneler",
  "ev.4.name": "Patlayan Stadyum",
  "ev.4.mechanic": "4S Stadyum sayaçları",
  "ev.5.name": "Yetenek Antrenmanı",
  "ev.5.mechanic": "Genç oyuncu gelişimi",
  "ev.6.name": "Efsaneler",
  "ev.6.mechanic": "Efsaneler Transfer Listesinde",
  "ev.7.name": "Süper Hızlı Antrenör",
  "ev.7.mechanic": "Normal antrenörler 2S, Evrensel Antrenör 1S",
  "ev.8.name": "Yoğun Hazırlık Maçları",
  "ev.8.mechanic": "Hazırlık maçlarıyla ekstra gelişim",
  // Stats + disclaimer
  "stats.world": "DÜNYA NO. 1 MİRASI",
  "disclaimer.coach_label": "ANTRENÖR UYARISI",
  // Formation styles
  "style.counter_attack": "Kontra Atak",
  "style.wing_play": "Kanat Oyunu",
  "style.shoot_on_sight": "Fırsatta Vur",
  "style.passing_game": "Pas Oyunu",
  // Month names (full)
  "months.january": "Ocak", "months.february": "Şubat", "months.march": "Mart",
  "months.april": "Nisan", "months.may": "Mayıs", "months.june": "Haziran",
  "months.july": "Temmuz", "months.august": "Ağustos", "months.september": "Eylül",
  "months.october": "Ekim", "months.november": "Kasım", "months.december": "Aralık",
  // Events header
  "events.program_title": "Programı",
  // Tactical engine interactive labels
  "tactical.step1": "1. Adım: Maç Konumu",
  "tactical.step2": "2. Adım: Rakip Taktik",
  "tactical.step3": "3. Adım: Kadro Gücü",
  "tactical.home": "EVİMİZDE",
  "tactical.away": "DEPLASMAN",
  "tactical.stronger": "GÜÇLÜYÜZ",
  "tactical.equal": "EŞİTİZ",
  "tactical.weaker": "ZAYIFIZ",
  // Football pitch line-tactics labels
  "pitch.lineTactics": "ÇİZGİ TAKTİKLERİ",
  "pitch.attackOnly": "Sadece Hücum",
  "pitch.protectDefense": "Defansa Yardım",
  "pitch.stayBack": "Geride Kal",
  "pitch.defendDeep": "Derin Savunma",
  "pitch.zoneMarking": "Alan Markajı",
  "pitch.manMarking": "Adam Markajı",
  "pitch.offsideNo": "Ofsayt Tuzağı: Hayır",
  "pitch.offsideYes": "Ofsayt Tuzağı: Evet",
  // Coach notes by tactic index (falls back to English database note if key missing)
  "note.0":  "4-3-3 A karşısında deplasmanda zayıf: 5'li savunma bloğunu kur, baskıyı absorbe et. Kontrayla vur.",
  "note.1":  "4-3-3 A karşısında deplasmanda eşit: kontrollü kontra-baskı. Şekli koru, top kaybında ileriye fırla.",
  "note.2":  "4-3-3 A karşısında deplasmanda güçlü: hızlı geçişlerle cezalandır. Kanatları kazan, hızlı kır.",
  "note.3":  "4-3-3 A karşısında deplasmanda zayıf (alt): ultra kompakt 5-3-2 blok genişliği engeller — absorbe et, geç kontra yap.",
  "note.4":  "5-3-1-1 karşısında deplasmanda zayıf: sabır silahtır. Onlar park eder — absorbe et, fırsatta kontra yap.",
  "note.5":  "5-3-1-1 karşısında deplasmanda eşit: kontrollü genişlik ve hızlı geçişlerle savunma kabuğunu kır.",
  "note.6":  "5-3-1-1 karşısında deplasmanda güçlü: hızlı kontra koşularıyla savunma çizgisinin arkasındaki alanı değerlendir.",
  "note.7":  "5-3-2 karşısında deplasmanda güçlü: hızlı kontra kombinasyonlarıyla kompakt bloklarını kır. Kaliteni kullan.",
  "note.8":  "5-3-2 karşısında deplasmanda eşit: disiplini yansıt — daha iyi düzen ve tempoyla kontraları kazan.",
  "note.9":  "5-3-2 karşısında deplasmanda güçlü (alt): yüksek tempolu kontra — toparlanmadan önce geçişleri aşır.",
  "note.10": "5-2-3 karşısında deplasmanda zayıf: kontrayı kontrayla geç. Onlar hücum eder — absorbe et, daha hızlı cezalandır.",
  "note.11": "5-2-3 karşısında deplasmanda eşit: keskin karar verme kazandırır. Top kaybında orta saha düellosunu al.",
  "note.12": "5-2-3 karşısında deplasmanda güçlü: baskıyı kademeli artır, üstünlüğünü geçiş gollerine çevir.",
  "note.13": "4-2-3-1 karşısında deplasmanda zayıf: 5'li düşük savunma şarttır. Sıfır baskı — tek fırsatı bekle.",
  "note.14": "4-2-3-1 karşısında deplasmanda eşit: uzak şutları 5'li kontra düzeniyle etkisizleştir. Kompakt kal.",
  "note.15": "4-2-3-1 karşısında deplasmanda güçlü: onları kendi yarısına hapset. Kontra-baskı yap, geçiş alanına hükmet.",
  "note.16": "4-5-1 karşısında deplasmanda zayıf: 5-2-3 kontrası orta sahalarını kapatır. Sabırlı ol — fırsat gelecek.",
  "note.17": "4-5-1 karşısında deplasmanda eşit: 5'li orta sahasına 5'li savunmayla yanıt ver. Geniş kanallardan kontra yap.",
  "note.18": "4-5-1 karşısında deplasmanda güçlü: yüksek tempolu kontrayla oyun kuruluşlarını boğ. Geçişleri değerlendir.",
  "note.19": "4-3-3 B karşısında deplasmanda zayıf: aynı kilitleme yaklaşımı — 5'li kompakt blok, fırsatta kontra.",
  "note.20": "4-3-3 B karşısında deplasmanda eşit: kontrollü top kaybettirme. Hata yaptır, klinik hassasiyetle kontra yap.",
  "note.21": "4-3-3 B karşısında deplasmanda güçlü: baskın kontra. Tempoyu yükselt, her geçişi değerlendir.",
  "note.22": "4-3-3 B karşısında deplasmanda zayıf (alt): ultra kompakt 5-3-2 blok kanat tehditlerini tamamen siler.",
  "note.23": "4-4-2 Pas Oyunu karşısında deplasmanda zayıf: 4-5-1 Fırsatta Vur orta sahadaki üstünlüklerini etkisizleştirir.",
  "note.24": "4-4-2 karşısında deplasmanda eşit: pas ritmini boz, hızlı kontralarla açık alanları değerlendir.",
  "note.25": "4-4-2 karşısında deplasmanda güçlü: 4-3-3 B kanat oyunuyla açık kanatlarına saldır. Geniş savaşları kazan.",
  "note.26": "4-4-2 karşısında deplasmanda eşit (alt): 5-2-3 pas oyunlarını emer, hassasiyetle kontra yapar.",
  "note.27": "5-4-1 karşısında deplasmanda zayıf: aşırı sabır gerekli. Onları oturtur — fazla ilerlediğinde kontra yap.",
  "note.28": "5-4-1 karşısında deplasmanda eşit: dengeli kontra savunma kabuğunu kırar. Sisteme güven.",
});

Object.assign(extraTranslations.hu, {
  "stats.world": "VILÁG #1 ÖRÖKSÉG",
  "disclaimer.coach_label": "EDZŐ FIGYELMEZTETÉS",
  "style.counter_attack": "Kontramanőver", "style.wing_play": "Szárny Játék",
  "style.shoot_on_sight": "Kapura Lőj", "style.passing_game": "Passjáték",
  "months.january": "Január", "months.february": "Február", "months.march": "Március",
  "months.april": "Április", "months.may": "Május", "months.june": "Június",
  "months.july": "Július", "months.august": "Augusztus", "months.september": "Szeptember",
  "months.october": "Október", "months.november": "November", "months.december": "December",
  "events.program_title": "Program",
  "events.disclaimer": "Valós idejű frissítés · UK időzóna",
  "events.status.finished": "BEFEJEZVE",
  "events.status.upcoming": "HAMAROSAN",
  "ev.0.name": "Extrém Edzés",
  "ev.0.mechanic": "Gyorsabb edzés: 2Ó normál, 1:30Ó Univerzális",
  "ev.1.name": "Átigazolási Őrület",
  "ev.1.mechanic": "6 játékos a listán, 2Ó Cserkész",
  "ev.2.name": "Garantált Edzési Boost",
  "ev.2.mechanic": "Nincs normál edzés — Gyors edzés: 4Ó / 3Ó",
  "ev.3.name": "Veteránok × Legendák",
  "ev.3.mechanic": "Idős játékosok fejlődése, Legendák a listán",
  "ev.4.name": "Robbanó Stadion",
  "ev.4.mechanic": "4Ó Stadion időzítők",
  "ev.5.name": "Tehetség Edzés",
  "ev.5.mechanic": "Fiatal játékosok fejlődése",
  "ev.6.name": "Legendák",
  "ev.6.mechanic": "Legendák az Átigazolási Listán",
  "ev.7.name": "Szupergyors Edző",
  "ev.7.mechanic": "2Ó normál edzők, 1Ó Univerzális Edző",
  "ev.8.name": "Intenzív Barátságos Meccsek",
  "ev.8.mechanic": "Extra fejlődés Barátságos meccsekkel",
  // Tactical engine interactive labels
  "tactical.step1": "1. lépés: Helyszín",
  "tactical.step2": "2. lépés: Ellenfél taktikája",
  "tactical.step3": "3. lépés: Keret erőssége",
  "tactical.home": "OTTHON",
  "tactical.away": "VENDÉG",
  "tactical.stronger": "ERŐSEBB",
  "tactical.equal": "EGYENLŐ",
  "tactical.weaker": "GYENGÉBB",
  // Football pitch line-tactics labels
  "pitch.lineTactics": "VONALTAKTIKÁK",
  "pitch.attackOnly": "Csak Támadás",
  "pitch.protectDefense": "Védekezés Segítség",
  "pitch.stayBack": "Marad Hátrébb",
  "pitch.defendDeep": "Mély Védekezés",
  "pitch.zoneMarking": "Zónamarkálás",
  "pitch.manMarking": "Egyesmarkálás",
  "pitch.offsideNo": "Lesen csapda: Nem",
  "pitch.offsideYes": "Lesen csapda: Igen",
  "mentality.wingPlay":      "Szárny Játék",
  "mentality.passingGame":   "Passjáték",
  "mentality.shootOnSight":  "Kapura Lőj",
  "mentality.counterAttack": "Kontramanőver",
  "mentality.longBall":      "Hosszú Labda",
  "alternative.title":   "NAGY ÉRTÉKŰ ALTERNATÍV TAKTIKA",
  "alternative.desc":    "Az otthoni mérkőzéseken minden ellenféllel szemben folyamatosan alkalmazott egyedi taktikai konfigurációnk.",
  "alternative.winRate": "GYŐZÉSI ARÁNY 95%",
  "anti.tacticsToday": "Ma Generált Taktika",
});

Object.assign(extraTranslations.ar, {
  "stats.world": "إرث رقم 1 عالمياً",
  "disclaimer.coach_label": "تحذير المدرب",
  "style.counter_attack": "هجوم ارتداد", "style.wing_play": "اللعب بالجناح",
  "style.shoot_on_sight": "التصويب الفوري", "style.passing_game": "لعبة التمرير",
  "months.january": "يناير", "months.february": "فبراير", "months.march": "مارس",
  "months.april": "أبريل", "months.may": "مايو", "months.june": "يونيو",
  "months.july": "يوليو", "months.august": "أغسطس", "months.september": "سبتمبر",
  "months.october": "أكتوبر", "months.november": "نوفمبر", "months.december": "ديسمبر",
  "events.program_title": "البرنامج",
  "events.disclaimer": "تحديث فوري · توقيت المملكة المتحدة",
  "events.status.finished": "انتهى",
  "events.status.upcoming": "قادم",
  "ev.0.name": "تدريب مكثف",
  "ev.0.mechanic": "تدريب أسرع: ساعتان عادي، 1:30س عالمي",
  "ev.1.name": "جنون الانتقالات",
  "ev.1.mechanic": "6 لاعبين في القائمة، 2س كشاف",
  "ev.2.name": "تعزيز التدريب المضمون",
  "ev.2.mechanic": "لا تدريبات عادية — تدريب سريع: 4س / 3س",
  "ev.3.name": "النجوم القدامى × الأساطير",
  "ev.3.mechanic": "تطور اللاعبين القدامى، الأساطير في القائمة",
  "ev.4.name": "الملعب المزدهر",
  "ev.4.mechanic": "مؤقتات الملعب 4س",
  "ev.5.name": "تدريب المواهب",
  "ev.5.mechanic": "تطور اللاعبين الشباب",
  "ev.6.name": "الأساطير",
  "ev.6.mechanic": "الأساطير في قائمة الانتقالات",
  "ev.7.name": "المدرب الخارق السريع",
  "ev.7.mechanic": "مدربون عاديون 2س، مدرب عالمي 1س",
  "ev.8.name": "المباريات الودية المكثفة",
  "ev.8.mechanic": "تطور إضافي مع المباريات الودية",
  // Tactical engine interactive labels
  "tactical.step1": "الخطوة 1: الملعب",
  "tactical.step2": "الخطوة 2: تكتيك الخصم",
  "tactical.step3": "الخطوة 3: قوة الفريق",
  "tactical.home": "في الديار",
  "tactical.away": "خارج",
  "tactical.stronger": "أقوى",
  "tactical.equal": "متساوون",
  "tactical.weaker": "أضعف",
  // Football pitch line-tactics labels
  "pitch.lineTactics": "تكتيكات الخطوط",
  "pitch.attackOnly": "هجوم فقط",
  "pitch.protectDefense": "مساعدة الدفاع",
  "pitch.stayBack": "البقاء خلفيًا",
  "pitch.defendDeep": "الدفاع العميق",
  "pitch.zoneMarking": "تركيز منطقة",
  "pitch.manMarking": "تركيز فردي",
  "pitch.offsideNo": "فخ التسلل: لا",
  "pitch.offsideYes": "فخ التسلل: نعم",
  "mentality.wingPlay":      "لعب الجناح",
  "mentality.passingGame":   "لعبة التمرير",
  "mentality.shootOnSight":  "التصويب الفوري",
  "mentality.counterAttack": "هجوم الارتداد",
  "mentality.longBall":      "الكرة الطويلة",
  "alternative.title":   "تكتيك بديل عالي القيمة",
  "alternative.desc":    "إعداد تكتيكي مخصص نستخدمه باستمرار في المنزل ضد أي تشكيلة خصم.",
  "alternative.winRate": "نسبة الفوز 95%",
  "anti.tacticsToday": "التكتيكات المولّدة اليوم",
});

Object.assign(extraTranslations.pt, {
  "stats.world": "LEGADO Nº 1 MUNDIAL",
  "disclaimer.coach_label": "AVISO DO TREINADOR",
  "style.counter_attack": "Contra-Ataque", "style.wing_play": "Jogo de Ala",
  "style.shoot_on_sight": "Rematar na Oportunidade", "style.passing_game": "Jogo de Passe",
  "months.january": "Janeiro", "months.february": "Fevereiro", "months.march": "Março",
  "months.april": "Abril", "months.may": "Maio", "months.june": "Junho",
  "months.july": "Julho", "months.august": "Agosto", "months.september": "Setembro",
  "months.october": "Outubro", "months.november": "Novembro", "months.december": "Dezembro",
  "events.program_title": "Programa",
  "events.disclaimer": "Atualiza em tempo real · Fuso horário UK",
  "events.status.finished": "ENCERRADO",
  "events.status.upcoming": "EM BREVE",
  "ev.0.name": "Treino Extremo",
  "ev.0.mechanic": "Treino mais rápido: 2H normal, 1:30H Universal",
  "ev.1.name": "Loucura das Transferências",
  "ev.1.mechanic": "6 jogadores na lista, 2H Scout",
  "ev.2.name": "Boost de Treino Garantido",
  "ev.2.mechanic": "Sem treinos normais — Treino rápido: 4H / 3H",
  "ev.3.name": "Veteranos × Lendas",
  "ev.3.mechanic": "Progressão de jogadores antigos, Lendas na lista",
  "ev.4.name": "Estádio em Expansão",
  "ev.4.mechanic": "Temporizadores de Estádio de 4H",
  "ev.5.name": "Talentos em Treino",
  "ev.5.mechanic": "Progressão de jogadores jovens",
  "ev.6.name": "Lendas",
  "ev.6.mechanic": "Lendas na Lista de Transferências",
  "ev.7.name": "Treinador Ultra Rápido",
  "ev.7.mechanic": "Treinadores normais 2H, Treinador Universal 1H",
  "ev.8.name": "Amistosos Intensos",
  "ev.8.mechanic": "Progressão extra com Amistosos",
  // Tactical engine interactive labels
  "tactical.step1": "Passo 1: Local",
  "tactical.step2": "Passo 2: Tática do Adversário",
  "tactical.step3": "Passo 3: Força do Elenco",
  "tactical.home": "CASA",
  "tactical.away": "FORA",
  "tactical.stronger": "MAIS FORTE",
  "tactical.equal": "IGUAL",
  "tactical.weaker": "MAIS FRACO",
  // Football pitch line-tactics labels
  "pitch.lineTactics": "TÁTICAS DE LINHA",
  "pitch.attackOnly": "Só Ataque",
  "pitch.protectDefense": "Ajudar Defesa",
  "pitch.stayBack": "Ficar Recuado",
  "pitch.defendDeep": "Defesa Profunda",
  "pitch.zoneMarking": "Marcação por Zona",
  "pitch.manMarking": "Marcação Individual",
  "pitch.offsideNo": "Armadilha Fora: Não",
  "pitch.offsideYes": "Armadilha Fora: Sim",
  "mentality.wingPlay":      "Jogo de Ala",
  "mentality.passingGame":   "Jogo de Passe",
  "mentality.shootOnSight":  "Rematar na Oportunidade",
  "mentality.counterAttack": "Contra-Ataque",
  "mentality.longBall":      "Bola Longa",
  "alternative.title":   "TÁTICA ALTERNATIVA DE ALTO VALOR",
  "alternative.desc":    "A nossa configuração tática personalizada usada consistentemente em casa contra qualquer formação adversária.",
  "alternative.winRate": "TAXA DE VITÓRIA 95%",
  "anti.tacticsToday": "Táticas Geradas Hoje",
});

Object.assign(extraTranslations.en, {
  "garage.label": "My Garage",
  "garage.title": "My Tactic Garage",
  "garage.sub":   "Your saved tactics",
});

Object.assign(extraTranslations.tr, {
  "garage.label": "Garajım",
  "garage.title": "Taktik Garajım",
  "garage.sub":   "Kaydettiğin taktikler",
});

Object.assign(extraTranslations.hu, {
  "garage.label": "Garázsam",
  "garage.title": "Taktika Garázsam",
  "garage.sub":   "Mentett taktikáid",
});

Object.assign(extraTranslations.ar, {
  "garage.label": "مرآبي",
  "garage.title": "مرآب التكتيكات",
  "garage.sub":   "تكتيكاتك المحفوظة",
});

Object.assign(extraTranslations.pt, {
  "garage.label": "Minha Garagem",
  "garage.title": "Minha Garagem de Táticas",
  "garage.sub":   "Suas táticas salvas",
});

Object.assign(extraTranslations.en, {
  "specialist.label": "Specialist Matrix",
  "specialist.title": "Specialist Selection Matrix",
  "specialist.sub":   "Captain · Penalty · Free Kick · Playmaker",
  "synergy.label":    "Nationality Synergy",
  "synergy.title":    "Nationality Synergy Tracker",
  "synergy.sub":      "Track the hidden +3 squad bonus",
});
Object.assign(extraTranslations.tr, {
  "specialist.label": "Uzman Matrisi",
  "specialist.title": "Uzman Seçim Matrisi",
  "specialist.sub":   "Kaptan · Penaltı · Serbest Vuruş · Oyun Kurucu",
  "synergy.label":    "Milliyet Sinerjisi",
  "synergy.title":    "Milliyet Sinerji Takibi",
  "synergy.sub":      "Gizli +3 kadro bonusunu takip et",
});
Object.assign(extraTranslations.hu, {
  "specialist.label": "Specialista Mátrix",
  "specialist.title": "Specialista Kiválasztási Mátrix",
  "specialist.sub":   "Kapitány · Büntetőrúgó · Szabadrúgó · Játékirányító",
  "synergy.label":    "Nemzetiségi Szinergia",
  "synergy.title":    "Nemzetiségi Szinergia Követő",
  "synergy.sub":      "Rejtett +3 csapat bónusz követése",
});
Object.assign(extraTranslations.ar, {
  "specialist.label": "مصفوفة المتخصصين",
  "specialist.title": "مصفوفة اختيار المتخصصين",
  "specialist.sub":   "القائد · ركلة الجزاء · الركلة الحرة · صانع اللعب",
  "synergy.label":    "تآزر الجنسيات",
  "synergy.title":    "متتبع تآزر الجنسيات",
  "synergy.sub":      "تتبع مكافأة الفريق المخفية +3",
});
Object.assign(extraTranslations.pt, {
  "specialist.label": "Matriz de Especialistas",
  "specialist.title": "Matriz de Seleção de Especialistas",
  "specialist.sub":   "Capitão · Pênalti · Falta · Armador",
  "synergy.label":    "Sinergia de Nacionalidades",
  "synergy.title":    "Rastreador de Sinergia",
  "synergy.sub":      "Rastreie o bônus oculto +3 do elenco",
});

Object.assign(extraTranslations.tr, {
  "premium.heroBadge":        "VIP TAKTİK KOLEKSİYONU",
  "premium.heroLive":         "HAZİRAN 2026 GÜNCEL",
  "premium.heroTitleA":       "Ömer'in",
  "premium.heroTitleB":       "Gizli VIP",
  "premium.heroTitleC":       "Taktikleri",
  "premium.heroDesc":         "Final, kupa ve kritik maçlar için özel optimize edilmiş — sıradan anti-taktik motorunda bulunmayan VIP setler.",
  "premium.feat1":            "5-2-3 Kontra Atak (Ev) — %85 kazanma · Her rakibe karşı",
  "premium.feat2":            "4-3-3 A Wing Play (Ev) — Rank 4-10 için optimize",
  "premium.feat3":            "4-3-3 B (Ev) — 5-2-3 oynayan rakibe özel",
  "premium.feat4":            "5-2-3 Kontra (Deplasman) — Sabit · Her rakibe karşı",
  "premium.codeHave":         "🔑 Kodum var",
  "premium.joinBefore":       "Bu hafta",
  "premium.joinAfter":        "kişi katıldı",
  "premium.statLabel1":       "VIP Taktik",
  "premium.statSub1":         "Aktif Set",
  "premium.statLabel2":       "Kazanma Oranı",
  "premium.statSub2":         "Ev Maçları",
  "premium.statLabel3":       "Güncelleme",
  "premium.statSub3":         "Canlı Takip",
  "premium.secureNote":       "Bu taktikler yalnızca sana özeldir. Paylaşmak taktiği geçersiz kılar — yaygınlaşan taktikler motor tarafından dengelenir.",
  "premium.secureNoteActive": "Bu taktikleri asla başkasıyla paylaşma! Çok kişi kullanınca sistem patlıyor ve taktik geçersiz hale geliyor.",
  "premium.vipRequired":      "VIP Erişim Gerekli",
  "premium.winRateSuffix":    "Kazanma",
  "premium.effective":        "Etkili:",
  "premium.offside":          "Ofsayt:",
  "premium.pressure":         "Baskı",
  "premium.style":            "Stil",
  "premium.tempo":            "Tempo",
  "premium.lineForward":      "Forvet",
  "premium.lineMidfield":     "Orta Saha",
  "premium.lineDefense":      "Defans",
  "premium.locHome":          "EV",
  "premium.locAway":          "DEPLASMAN",
  "ptv.kontraAtak":           "Kontra Atak",
  "ptv.kanatKullan":          "Kanatları Kullan",
  "ptv.sadeceHucum":          "Sadece Hücum",
  "ptv.defansYardim":         "Defans Yardım",
  "ptv.pozisyonKoru":         "Pozisyon Koru",
  "ptv.geridKal":             "Geride Kal",
  "ptv.alanSavunmasi":        "Alan Savunması",
  "ptv.kapali":               "Kapalı",
  "ptv.kapaliStar":           "Kapalı*",
  "ptactic.june-home-523.name":     "5-2-3 Kontra Atak",
  "ptactic.june-home-523.scenario": "Evde · Rakip ne oynarsa oynasın",
  "ptactic.june-home-523.note":     "Rakip ne oynarsa oynasın, bu taktik çalışıyor. Haziran 2026'nın en güçlü ev taktiği.",
  "ptactic.june-home-523.warning":  "Güncelleme gelirse sayılar değişebilir. Takip et!",
  "ptactic.june-home-433a.name":    "4-3-3 A · Kanatları Kullan",
  "ptactic.june-home-433a.scenario":"Evde · Rank 4-10 arası güçlüyken",
  "ptactic.june-home-433a.note":    "4-10 rank arası güçlüyken kullan. 4-3-3 ve 5-2-3 oynayan rakiplere karşı son derece etkili.",
  "ptactic.june-home-433a.warning": "*Rakip kontra oynuyorsa ofsayt tuzağını aç.",
  "ptactic.june-home-433b.name":    "4-3-3 B · Kanatları Kullan",
  "ptactic.june-home-433b.scenario":"Evde · 5-2-3 oynayan rakibe karşı",
  "ptactic.june-home-433b.note":    "5-2-3 oynayan rakiplere karşı özel optimize edilmiş taktik. Kanat hücumları cevap vermek zordur.",
  "ptactic.june-home-433b.warning": "*Rakip kontra oynuyorsa ofsayt tuzağını aç.",
  "ptactic.june-away-523.name":     "5-2-3 Kontra Atak",
  "ptactic.june-away-523.scenario": "Deplasman · Sabit — her rakibe karşı kullan",
  "ptactic.june-away-523.note":     "Deplasman taktiği sabittir, değiştirme. Her rakibe karşı, her sıralamada bu taktiği kullan.",
});

Object.assign(extraTranslations.en, {
  "premium.heroBadge":        "VIP TACTIC COLLECTION",
  "premium.heroLive":         "JUNE 2026 UPDATED",
  "premium.heroTitleA":       "Omer's",
  "premium.heroTitleB":       "Secret VIP",
  "premium.heroTitleC":       "Tactics",
  "premium.heroDesc":         "Specially optimised for finals, cups and critical matches — VIP sets not found in the regular anti-tactic engine.",
  "premium.feat1":            "5-2-3 Counter Attack (Home) — 85% win rate · Works vs any opponent",
  "premium.feat2":            "4-3-3 A Wing Play (Home) — Optimised for Rank 4-10",
  "premium.feat3":            "4-3-3 B (Home) — Tailored vs opponents using 5-2-3",
  "premium.feat4":            "5-2-3 Counter (Away) — Fixed · Works vs any opponent",
  "premium.codeHave":         "🔑 I have a code",
  "premium.joinBefore":       "This week",
  "premium.joinAfter":        "people joined",
  "premium.statLabel1":       "VIP Tactics",
  "premium.statSub1":         "Active Sets",
  "premium.statLabel2":       "Win Rate",
  "premium.statSub2":         "Home Matches",
  "premium.statLabel3":       "Updates",
  "premium.statSub3":         "Live Tracking",
  "premium.secureNote":       "These tactics are for your eyes only. Sharing them invalidates the tactic — widespread use triggers engine rebalancing.",
  "premium.secureNoteActive": "Never share these tactics with anyone! Overuse crashes the system and renders the tactic invalid.",
  "premium.vipRequired":      "VIP Access Required",
  "premium.winRateSuffix":    "Win Rate",
  "premium.effective":        "Effective vs:",
  "premium.offside":          "Offside:",
  "premium.pressure":         "Pressure",
  "premium.style":            "Style",
  "premium.tempo":            "Tempo",
  "premium.lineForward":      "Forward",
  "premium.lineMidfield":     "Midfield",
  "premium.lineDefense":      "Defense",
  "premium.locHome":          "HOME",
  "premium.locAway":          "AWAY",
  "ptv.kontraAtak":           "Counter Attack",
  "ptv.kanatKullan":          "Use Wings",
  "ptv.sadeceHucum":          "Attack Only",
  "ptv.defansYardim":         "Help Defense",
  "ptv.pozisyonKoru":         "Hold Position",
  "ptv.geridKal":             "Stay Back",
  "ptv.alanSavunmasi":        "Zone Defense",
  "ptv.kapali":               "Off",
  "ptv.kapaliStar":           "Off*",
  "ptactic.june-home-523.name":     "5-2-3 Counter Attack",
  "ptactic.june-home-523.scenario": "Home · Works vs any opponent",
  "ptactic.june-home-523.note":     "This tactic works regardless of what the opponent plays. The strongest home tactic of June 2026.",
  "ptactic.june-home-523.warning":  "Numbers may change with updates. Stay tuned!",
  "ptactic.june-home-433a.name":    "4-3-3 A · Use Wings",
  "ptactic.june-home-433a.scenario":"Home · When stronger, Rank 4-10",
  "ptactic.june-home-433a.note":    "Use when stronger at Rank 4-10. Extremely effective against opponents using 4-3-3 and 5-2-3.",
  "ptactic.june-home-433a.warning": "*Open offside trap if opponent plays counter.",
  "ptactic.june-home-433b.name":    "4-3-3 B · Use Wings",
  "ptactic.june-home-433b.scenario":"Home · Against opponents using 5-2-3",
  "ptactic.june-home-433b.note":    "Specially optimised tactic against opponents using 5-2-3. Wing attacks are very hard to counter.",
  "ptactic.june-home-433b.warning": "*Open offside trap if opponent plays counter.",
  "ptactic.june-away-523.name":     "5-2-3 Counter Attack",
  "ptactic.june-away-523.scenario": "Away · Fixed — use vs any opponent",
  "ptactic.june-away-523.note":     "The away tactic is fixed, do not change it. Use this tactic in every ranking, against every opponent.",
});

Object.assign(extraTranslations.hu, {
  "premium.heroBadge":     "VIP TAKTIKAI KOLLEKCIÓ",
  "premium.heroLive":      "JÚNIUS 2026 FRISSÍTVE",
  "premium.heroTitleA":    "Omer",
  "premium.heroTitleB":    "Titkos VIP",
  "premium.heroTitleC":    "Taktikái",
  "premium.heroDesc":      "Döntőkre, kupákra és kritikus meccsekre optimalizálva — VIP készletek, amelyek nem találhatók az általános anti-taktika motorban.",
  "premium.codeHave":      "🔑 Van kódom",
  "premium.joinBefore":    "Ezen a héten",
  "premium.joinAfter":     "ember csatlakozott",
  "premium.vipRequired":   "VIP Hozzáférés Szükséges",
  "premium.winRateSuffix": "Győzelmi arány",
  "premium.effective":     "Hatékony:",
  "premium.offside":       "Lesállás:",
  "premium.pressure":      "Nyomás",
  "premium.style":         "Stílus",
  "premium.tempo":         "Tempó",
  "premium.lineForward":   "Csatár",
  "premium.lineMidfield":  "Középpálya",
  "premium.lineDefense":   "Védelem",
  "premium.locHome":       "HAZAI",
  "premium.locAway":       "VENDÉG",
});

Object.assign(extraTranslations.ar, {
  "premium.heroBadge":     "مجموعة التكتيكات VIP",
  "premium.heroLive":      "يونيو 2026 محدّث",
  "premium.heroTitleA":    "تكتيكات عمر",
  "premium.heroTitleB":    "VIP السرية",
  "premium.heroTitleC":    "",
  "premium.heroDesc":      "مُحسَّنة خصيصاً للنهائيات والكؤوس والمباريات الحاسمة — مجموعات VIP غير موجودة في محرك التكتيك المضاد العادي.",
  "premium.codeHave":      "🔑 لدي رمز",
  "premium.joinBefore":    "هذا الأسبوع",
  "premium.joinAfter":     "شخصاً انضم",
  "premium.vipRequired":   "مطلوب وصول VIP",
  "premium.winRateSuffix": "فوز",
  "premium.effective":     "فعّال ضد:",
  "premium.offside":       "تسلل:",
  "premium.pressure":      "الضغط",
  "premium.style":         "الأسلوب",
  "premium.tempo":         "الإيقاع",
  "premium.lineForward":   "الهجوم",
  "premium.lineMidfield":  "الوسط",
  "premium.lineDefense":   "الدفاع",
  "premium.locHome":       "ملعبنا",
  "premium.locAway":       "خارجي",
});

Object.assign(extraTranslations.pt, {
  "premium.heroBadge":     "COLEÇÃO TÁTICA VIP",
  "premium.heroLive":      "JUNHO 2026 ATUALIZADO",
  "premium.heroTitleA":    "As Táticas",
  "premium.heroTitleB":    "VIP Secretas",
  "premium.heroTitleC":    "do Omer",
  "premium.heroDesc":      "Optimizadas para finais, copas e jogos críticos — conjuntos VIP não encontrados no motor anti-tática regular.",
  "premium.codeHave":      "🔑 Tenho um código",
  "premium.joinBefore":    "Esta semana",
  "premium.joinAfter":     "pessoas entraram",
  "premium.vipRequired":   "Acesso VIP Necessário",
  "premium.winRateSuffix": "Vitórias",
  "premium.effective":     "Eficaz vs:",
  "premium.offside":       "Impedimento:",
  "premium.pressure":      "Pressão",
  "premium.style":         "Estilo",
  "premium.tempo":         "Ritmo",
  "premium.lineForward":   "Ataque",
  "premium.lineMidfield":  "Meio-Campo",
  "premium.lineDefense":   "Defesa",
  "premium.locHome":       "CASA",
  "premium.locAway":       "FORA",
});

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  langs: typeof LANGS;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = typeof window !== "undefined" ? localStorage.getItem("osm-lang") : null;
    return (saved as Lang) || "en";
  });

  useEffect(() => {
    localStorage.setItem("osm-lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  const t = (key: string): string => {
    return extraTranslations[lang]?.[key] || translations[lang]?.[key] || extraTranslations.en[key] || translations.en[key] || key;
  };

  const setLang = (l: Lang) => setLangState(l);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, langs: LANGS }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used inside LanguageProvider");
  return ctx;
}